package wehavecookies56.kk.lib;

public class Strings {

	public static final String tabKingdomKeys = "tabKingdomKeys";
	public static final String tabKingdomKeysBlocks = "tabKingdomKeysblocks";

	// Records
	public static final String Disc_Birth_by_Sleep_A_Link_to_the_Future_Name = "Birth by Sleep -A Link to the Future-", Disc_Darkness_of_the_Unknown_Name = "Darkness of the Unknown", Disc_Dearly_Beloved_Symphony_Version_Name = "Dearly Beloved -Symphony Version-", Disc_Dream_Drop_Distance_The_Next_Awakening_Name = "Dream Drop Distance -The Next Awakening-", Disc_Hikari_KINGDOM_Instrumental_Version_Name = "Hikari -KINGDOM Instrumental Version-", Disc_L_Oscurita_Dell_Ignoto_Name = "L'Oscurita Dell'Ignoto", Disc_Musique_pour_la_tristesse_de_Xion_Name = "Musique pour la tristesse de Xion", Disc_No_More_Bugs_Bug_Version_Name = "No More Bugs -Bug Version-", Disc_Organization_XIII_Name = "Organization XIII", Disc_Sanctuary_Name = "Sanctuary", Disc_Simple_And_Clean_PLANITb_Remix_Name = "Simple And Clean PLANITb Remix", Disc_Sinister_Sundown_Name = "Sinister Sundown", Disc_The_13th_Anthology_Name = "The 13th Anthology", Disc_Duration_Desc = "disc.duration.desc",
			Disc_DurationUnits_Desc = "disc.durationunits.desc";

	// Achievements
	public static final String Achievement_OpenMenu = "achievement.openmenu", Achievement_GetKeyblade = "achievement.getkeyblade", Achievement_GetWehavecookies56Skull = "achievement.getWehavecookies56Skull", Achievement_GetAbelatoxSkull = "achievement.getAbelatoxSkull", Achievement_GetBlox = "achievement.getblox", Achievement_GetSynthesisTable = "achievement.getSynthesisTable", Achievement_GetRecipe = "achievement.getrecipe"

	;

	// Gui
	public static final String
	// Command Menu
	Gui_CommandMenu = "gui.commandmenu", Gui_CommandMenu_Command = Gui_CommandMenu + ".command", Gui_CommandMenu_Attack = Gui_CommandMenu + ".attack", Gui_CommandMenu_Magic = Gui_CommandMenu + ".magic", Gui_CommandMenu_Items = Gui_CommandMenu + ".items", Gui_CommandMenu_Drive = Gui_CommandMenu + ".drive", Gui_CommandMenu_Magic_Title = Gui_CommandMenu_Magic + ".title",

			Gui_CommandMenu_Magic_Fire = Gui_CommandMenu_Magic + ".fire", Gui_CommandMenu_Magic_Fira = Gui_CommandMenu_Magic + ".fira", Gui_CommandMenu_Magic_Firaga = Gui_CommandMenu_Magic + ".firaga",

			Gui_CommandMenu_Magic_Blizzard = Gui_CommandMenu_Magic + ".blizzard", Gui_CommandMenu_Magic_Blizzara = Gui_CommandMenu_Magic + ".blizzara", Gui_CommandMenu_Magic_Blizzaga = Gui_CommandMenu_Magic + ".blizzaga",

			Gui_CommandMenu_Magic_Thunder = Gui_CommandMenu_Magic + ".thunder", Gui_CommandMenu_Magic_Thundara = Gui_CommandMenu_Magic + ".thundara", Gui_CommandMenu_Magic_Thundaga = Gui_CommandMenu_Magic + ".thundaga",

			Gui_CommandMenu_Magic_Cure = Gui_CommandMenu_Magic + ".cure", Gui_CommandMenu_Magic_Cura = Gui_CommandMenu_Magic + ".cura", Gui_CommandMenu_Magic_Curaga = Gui_CommandMenu_Magic + ".curaga",

			Gui_CommandMenu_Magic_Gravity = Gui_CommandMenu_Magic + ".gravity", Gui_CommandMenu_Magic_Gravira = Gui_CommandMenu_Magic + ".gravira", Gui_CommandMenu_Magic_Graviga = Gui_CommandMenu_Magic + ".graviga",

			Gui_CommandMenu_Magic_Aero = Gui_CommandMenu_Magic + ".aero", Gui_CommandMenu_Magic_Aerora = Gui_CommandMenu_Magic + ".aerora", Gui_CommandMenu_Magic_Aeroga = Gui_CommandMenu_Magic + ".aeroga",

			Gui_CommandMenu_Magic_Stop = Gui_CommandMenu_Magic + ".stop", Gui_CommandMenu_Magic_Stopra = Gui_CommandMenu_Magic + ".stopra", Gui_CommandMenu_Magic_Stopga = Gui_CommandMenu_Magic + ".stopga",

			Gui_CommandMenu_Drive_Title = Gui_CommandMenu_Drive + ".title", Gui_CommandMenu_Drive_Valor = Gui_CommandMenu_Drive + ".valor", Gui_CommandMenu_Drive_Wisdom = Gui_CommandMenu_Drive + ".wisdom", Gui_CommandMenu_Drive_Limit = Gui_CommandMenu_Drive + ".limit", Gui_CommandMenu_Drive_Master = Gui_CommandMenu_Drive + ".master", Gui_CommandMenu_Drive_Final = Gui_CommandMenu_Drive + ".final",

			// Menu
			Gui_Menu = "gui.menu", Gui_Menu_Main = Gui_Menu + ".main", Gui_Menu_Main_Title = Gui_Menu_Main + ".title", Gui_Menu_Main_Button = Gui_Menu_Main + ".button", Gui_Menu_Main_Button_Items = Gui_Menu_Main_Button + ".items", Gui_Menu_Main_Button_Abilities = Gui_Menu_Main_Button + ".abilities", Gui_Menu_Main_Button_Customize = Gui_Menu_Main_Button + ".customize", Gui_Menu_Main_Button_Party = Gui_Menu_Main_Button + ".party", Gui_Menu_Main_Button_Status = Gui_Menu_Main_Button + ".status", Gui_Menu_Main_Button_Journal = Gui_Menu_Main_Button + ".journal", Gui_Menu_Main_Button_Config = Gui_Menu_Main_Button + ".config", Gui_Menu_Main_Time = Gui_Menu_Main + ".time", Gui_Menu_Items = Gui_Menu + ".items", Gui_Menu_Items_Title = Gui_Menu_Items + ".title", Gui_Menu_Items_Player = Gui_Menu_Items + ".player", Gui_Menu_Items_Button_Keychain = Gui_Menu_Items + ".keychain", Gui_Menu_Items_Button_SynthBag = Gui_Menu_Items + ".synthbag", Gui_Menu_Items_Button = Gui_Menu_Items + ".button",
			Gui_Menu_Items_Button_Stock = Gui_Menu_Items_Button + ".stock", Gui_Menu_Items_Button_Back = Gui_Menu_Items_Button + ".back", Gui_Menu_Main_Munny = Gui_Menu_Main + ".munny",

			// Synthesis
			Gui_Synthesis = "gui.synthesis", Gui_Synthesis_Main = Gui_Synthesis + ".main", Gui_Synthesis_Main_Title = Gui_Synthesis_Main + ".title", Gui_Synthesis_Main_Recipes = Gui_Synthesis_Main + ".recipes", Gui_Synthesis_Main_FreeDev = Gui_Synthesis_Main + ".freedevelopment", Gui_Synthesis_Main_Materials = Gui_Synthesis_Main + ".materials", Gui_Synthesis_Main_Recipes_ReqMaterials = Gui_Synthesis_Main_Recipes + ".requiredmaterials", Gui_Synthesis_Main_Recipes_Create = Gui_Synthesis_Main_Recipes + ".create";

	// Blocks
	public static final String
	// Blox
	NormalBlox = "normalblox", HardBlox = "hardblox", MetalBlox = "metalblox", DangerBlox = "dangerblox", BounceBlox = "bounceblox", BlastBlox = "blastblox", PrizeBlox = "prizeblox", RarePrizeBlox = "rareprizeblox", GhostBlox = "ghostblox", MagnetBlox = "magnetblox",

			KKChest = "kkchest",

			// Ores
			BlazingOre = "blazingore", BrightOre = "brightore", DarkOre = "darkore", DarkOreE = "darkoree", DenseOre = "denseore", EnergyOre = "energyore", FrostOre = "frostore", LucidOre = "lucidore", LightningOre = "lightningore", PowerOre = "powerore", PowerOreE = "poweroree", RemembranceOre = "remembranceore", SerenityOre = "serenityore", StormyOre = "stormyore", TranquilOre = "tranquilore", TwilightOre = "twilightore",

			// Others
			SynthesisTable = "synthesistable", SavePoint = "savepoint";

	// Tooltips
	public static final String HoldForInfo = "holdforinfo.desc", GhostBloxDesc = "tile.ghostblox.desc", DangerBloxDesc = "tile.dangerblox.desc", BounceBloxDesc = "tile.bounceblox.desc", KKChestDesc_1 = "tile.kkchest.desc1", KKChestDesc_2 = "tile.kkchest.desc2", SavePointDesc = "tile.savepoint.desc", SynthesisBagDesc = "By holding the synthesis bag in your inventory items will be sent into the synthesis table";

	// Items
	public static final String Munny = "munny", EmptyBottle = "emptybottle", Potion = "potion", Ether = "ether", Elixir = "elixir", HpOrb = "hporb", DriveOrb = "driveorb", MagicOrb = "magicorb", Heart = "heart", DarkHeart = "darkheart", PureHeart = "pureheart", KingdomHearts = "kingdomhearts", DarkLeather = "darkleather", SynthesisMaterial = "synthesismaterial", Recipe = "recipe", LunaticDesc = "item.lunatic.desc", IceCream = "icecream", WinnerStick = "winnerstick", LevelUpMagicFire = "levelupmagicfire", LevelUpMagicBlizzard = "levelupmagicblizzard", LevelUpMagicThunder = "levelupmagicthunder", LevelUpMagicCure = "levelupmagiccure", LevelUpMagicAero = "levelupmagicaero", LevelUpMagicStop = "levelupmagicstop", LevelUpValor = "levelupdrivevalor", LevelUpWisdom = "levelupdrivewisdom", LevelUpLimit = "levelupdrivelimit", LevelUpMaster = "levelupdrivemaster", LevelUpFinal = "levelupdrivefinal", SynthesisBagS = "synthesisbags", SynthesisBagM = "synthesisbagm",
			SynthesisBagL = "synthesisbagl";

	public static final String BlazingInfusedCoal = "blazinginfusedcoal", FrostInfusedSnowBall = "frostinfusedsnowball", StormyInfusedIron = "stormyinfusediron", MythrilInfusedDiamond = "mythrilinfuseddiamond", LightningInfusedGold = "lightninginfusedgold", BrightInfusedGlowStone = "brightinfusedglowstone", DarkInfusedIron = "darkinfusediron";

	// Armour
	public static final String OrganizationRobe_Helmet = "organizationrobe_helmet", OrganizationRobe_Chestplate = "organizationrobe_chestplate", OrganizationRobe_Leggings = "organizationrobe_leggings", OrganizationRobe_Boots = "organizationrobe_boots",

			Terra_Helmet = "terra_helmet", Terra_Chestplate = "terra_chestplate", Terra_Leggings = "terra_leggings", Terra_Boots = "terra_boots",

			Aqua_Helmet = "aqua_helmet", Aqua_Chestplate = "aqua_chestplate", Aqua_Leggings = "aqua_leggings", Aqua_Boots = "aqua_boots",

			Ventus_Helmet = "ventus_helmet", Ventus_Chestplate = "ventus_chestplate", Ventus_Leggings = "ventus_leggings", Ventus_Boots = "ventus_boots",

			Eraqus_Helmet = "eraqus_helmet", Eraqus_Chestplate = "eraqus_chestplate", Eraqus_Leggings = "eraqus_leggings", Eraqus_Boots = "eraqus_boots";

	// Synthesis Materials
	public static final String SM_Rank = "sm.rank", SM_BlazingShard = "sm.blazingshard", SM_BlazingStone = "sm.blazingstone", SM_BlazingGem = "sm.blazinggem", SM_BlazingCrystal = "sm.blazingcrystal",

			SM_BrightShard = "sm.brightshard", SM_BrightStone = "sm.brightstone", SM_BrightGem = "sm.brightgem", SM_BrightCrystal = "sm.brightcrystal",

			SM_DarkShard = "sm.darkshard", SM_DarkStone = "sm.darkstone", SM_DarkGem = "sm.darkgem", SM_DarkCrystal = "sm.darkcrystal",

			SM_DenseShard = "sm.denseshard", SM_DenseStone = "sm.densestone", SM_DenseGem = "sm.densegem", SM_DenseCrystal = "sm.densecrystal",

			SM_EnergyShard = "sm.energyshard", SM_EnergyStone = "sm.energystone", SM_EnergyGem = "sm.energygem", SM_EnergyCrystal = "sm.energycrystal",

			SM_FrostShard = "sm.frostshard", SM_FrostStone = "sm.froststone", SM_FrostGem = "sm.frostgem", SM_FrostCrystal = "sm.frostcrystal",

			SM_LightningShard = "sm.lightningshard", SM_LightningStone = "sm.lightningstone", SM_LightningGem = "sm.lightninggem", SM_LightningCrystal = "sm.lightningcrystal",

			SM_LucidShard = "sm.lucidshard", SM_LucidStone = "sm.lucidstone", SM_LucidGem = "sm.lucidgem", SM_LucidCrystal = "sm.lucidcrystal",

			SM_PowerShard = "sm.powershard", SM_PowerStone = "sm.powerstone", SM_PowerGem = "sm.powergem", SM_PowerCrystal = "sm.powercrystal",

			SM_MythrilShard = "sm.mythrilshard", SM_MythrilStone = "sm.mythrilstone", SM_MythrilGem = "sm.mythrilgem", SM_MythrilCrystal = "sm.mythrilcrystal",

			SM_RemembranceShard = "sm.remembranceshard", SM_RemembranceStone = "sm.remembrancestone", SM_RemembranceGem = "sm.remembrancegem", SM_RemembranceCrystal = "sm.remembrancecrystal",

			SM_SerenityShard = "sm.serenityshard", SM_SerenityStone = "sm.serenitystone", SM_SerenityGem = "sm.serenitygem", SM_SerenityCrystal = "sm.serenitycrystal",

			SM_TranquilShard = "sm.tranquilshard", SM_TranquilStone = "sm.tranquilstone", SM_TranquilGem = "sm.tranquilgem", SM_TranquilCrystal = "sm.tranquilcrystal",

			SM_TwilightShard = "sm.twilightshard", SM_TwilightStone = "sm.twilightstone", SM_TwilightGem = "sm.twilightgem", SM_TwilightCrystal = "sm.twilightcrystal",

			SM_Orichalcum = "sm.orichalcum", SM_OrichalcumPlus = "sm.orichalcum+", SM_ManifestIllusion = "sm.manifestillusion", SM_LostIllusion = "sm.lostillusion",

			SM_StormyShard = "sm.stormyshard", SM_StormyStone = "sm.stormystone", SM_StormyGem = "sm.stormygem", SM_StormyCrystal = "sm.stormycrystal";

	// Music Discs
	public static final String Disc_Birth_by_Sleep_A_Link_to_the_Future = "birthbysleep-alinktothefuture-", Disc_Darkness_of_the_Unknown = "darknessoftheunknown", Disc_Dearly_Beloved_Symphony_Version = "dearlybeloved-symphonyversion-", Disc_Dream_Drop_Distance_The_Next_Awakening = "dreamdropdistance-thenextawakening-", Disc_Hikari_KINGDOM_Instrumental_Version = "hikari-kingdominstrumentalversion-", Disc_L_Oscurita_Dell_Ignoto = "l'oscuritadell'ignoto", Disc_Musique_pour_la_tristesse_de_Xion = "musiquepourlatristessedexion", Disc_No_More_Bugs_Bug_Version = "nomorebugs-bugversion-", Disc_Organization_XIII = "organizationxiii", Disc_Sanctuary = "sanctuary", Disc_Simple_And_Clean_PLANITb_Remix = "simpleandcleanplanitbremix", Disc_Sinister_Sundown = "sinistersundown", Disc_The_13th_Anthology = "the13thanthology";

	// Organization
	public static final String Interdiction = "interdiction", Sharpshooter = "sharpshooter", Lindworm = "lindworm", FrozenPride = "frozenpride", Skysplitter = "skysplitter", BookofRetribution = "bookofretribution", Lunatic = "lunatic", EternalFlames = "eternalflames", Arpeggio = "arpeggio", FairGame = "fairgame", GracefulDahlia = "gracefuldahlia", Foudre = "foudre", BlazeofGlory = "blazeofglory", Prometheus = "prometheus", Ifrit = "ifrit";

	public static final String AbandonedKnowledge = "abandonedknowledge", DarkKnowledge = "darkknowledge", EclipsedKnowledge = "eclipsedknowledge", ForgottenKnowledge = "forgottenknowledge", IlludedKnowledge = "illudedknowledge", LostKnowledge = "lostknowledge", ManifestKnowledge = "manifestknowledge", ObscuredKnowledge = "obscuredknowledge", UnknownKnowledge = "unknownknowledge", VoidKnowledge = "voidknowledge";

	// Keyblades
	public static final String KingdomKey = "kingdomkey", Oathkeeper = "oathkeeper", Oblivion = "oblivion", UltimaWeaponKH1 = "ultimaweaponkh1", KingdomKeyD = "kingdomkeyd", KeybladeofPeoplesHearts = "keybladeofpeopleshearts", LadyLuck = "ladyluck", Olympia = "olympia", JungleKing = "jungleking", ThreeWishes = "threewishes", Crabclaw = "crabclaw", FairyHarp = "fairyharp", DivineRose = "divinerose", Spellbinder = "spellbinder", MetalChocobo = "metalchocobo", Lionheart = "lionheart", DiamondDust = "diamonddust", OneWingedAngel = "onewingedangel", SoulEater = "souleater", Pumpkinhead = "pumpkinhead", WishingStar = "wishingstar", BondofFlame = "bondofflame", FollowtheWind = "followthewind", HiddenDragon = "hiddendragon", Monochrome = "monochrome", PhotonDebugger = "photondebugger", StarSeeker = "starseeker", MaverickFlare = "maverickflare", TotalEclipse = "totaleclipse", MidnightRoar = "midnightroar", TwoBecomeOne = "twobecomeone", UltimaWeaponKH2 = "ultimaweaponkh2",
			WaytotheDawn = "waytothedawn", DestinysEmbrace = "destinysembrace", Stormfall = "stormfall", EndsoftheEarth = "endsoftheearth", RumblingRose = "rumblingrose", HerosCrest = "heroscrest", MysteriousAbyss = "mysteriousabyss", WishingLamp = "wishinglamp", DecisivePumpkin = "decisivepumpkin", CircleofLife = "circleoflife", SweetMemories = "sweetmemories", GullWing = "gullwing", GuardianSoul = "guardiansoul", SleepingLion = "sleepinglion", Fenrir = "fenrir", FatalCrest = "fatalcrest", WinnersProof = "winnersproof", MissingAche = "missingache", OminousBlight = "ominousblight", AbaddonPlasma = "abaddonplasma", PainofSolitude = "painofsolitude", SignofInnocence = "signofinnocence", CrownofGuilt = "crownofguilt", AbyssalTide = "abyssaltide", Leviathan = "leviathan", TrueLightsFlight = "truelightsflight", RejectionofFate = "rejectionoffate", GlimpseofDarkness = "glimpseofdarkness", SilentDirge = "silentdirge", LunarEclipse = "lunareclipse", DarkerThanDark = "darkerthandark",
			AstralBlast = "astralblast", TwilightBlaze = "twilightblaze", OmegaWeapon = "omegaweapon", Umbrella = "umbrella", Aubade = "aubade", WoodenStick = "woodenstick", DreamSword = "dreamsword", ZeroOne = "zeroone", Earthshaker = "earthshaker", Darkgnaw = "darkgnaw", ChaosRipper = "chaosripper", MasterXehanortsKeyblade = "masterxehanortskeyblade", TreasureTrove = "treasuretrove", StrokeofMidnight = "strokeofmidnight", FairyStars = "fairystars", VictoryLine = "victoryline", MarkofaHero = "markofahero", Hyperdrive = "hyperdrive", PixiePetal = "pixiepetal", Sweetstack = "sweetstack", UltimaWeaponBBS = "ultimaweaponbbs", VoidGear = "voidgear", NoName = "noname", RoyalRadiance = "royalradiance", Rainfell = "rainfell", Brightcrest = "brightcrest", MastersDefender = "mastersdefender", WaywardWind = "waywardwind", FrolicFlame = "frolicflame", LostMemory = "lostmemory", Kiblade = "kiblade", IncompleteKiblade = "incompletekiblade", WoodenKeyblade = "woodenkeyblade",
			SkullNoise = "skullnoise", GuardianBell = "guardianbell", DualDisc = "dualdisc", FerrisGear = "ferrisgear", KnockoutPunch = "knockoutpunch", AllforOne = "allforone", Counterpoint = "counterpoint", Divewing = "divewing", SweetDreams = "sweetdreams", UltimaWeaponDDD = "ultimaweaponddd", Unbound = "unbound", EndofPain = "endofpain", OceansRage = "oceansrage", LeasKeyblade = "leaskeyblade", YoungXehanortsKeyblade = "youngxehanortskeyblade", MirageSplit = "miragesplit", NightmaresEnd = "nightmaresend", NightmaresEndandMirageSplit = "nightmaresendandmiragesplit", Starlight = "starlight", AnguisForetellersKeyblade = "anguisforetellerskeyblade", LeopardosForetellersKeyblade = "leopardosforetellerskeyblade", UnicornisForetellersKeyblade = "unicornisforetellerskeyblade", UrsusForetellersKeyblade = "ursusforetellerskeyblade", VulpeusForetellersKeyblade = "vulpeusforetellerskeyblade";

	// CHAINS
	public static final String Chain_AbaddonPlasma = "abaddonplasmachain", Chain_AbyssalTide = "abyssaltidechain", Chain_AllforOne = "allforonechain", Chain_AnguisForetellersKeyblade = "anguisforetellerskeybladechain", Chain_AstralBlast = "astralblastchain", Chain_Aubade = "aubadechain", Chain_BondofFlame = "bondofflamechain", Chain_Brightcrest = "brightcrestchain", Chain_ChaosRipper = "chaosripperchain", Chain_CircleofLife = "circleoflifechain", Chain_Counterpoint = "counterpointchain", Chain_Crabclaw = "crabclawchain", Chain_CrownofGuilt = "crownofguiltchain", Chain_DarkerThanDark = "darkerthandarkchain", Chain_Darkgnaw = "darkgnawchain", Chain_DecisivePumpkin = "decisivepumpkinchain", Chain_DestinysEmbrace = "destinysembracechain", Chain_DiamondDust = "diamonddustchain", Chain_Divewing = "divewingchain", Chain_DivineRose = "divinerosechain", Chain_DreamSword = "dreamswordchain", Chain_DualDisc = "dualdiscchain", Chain_Earthshaker = "earthshakerchain",
			Chain_EndofPain = "endofpainchain", Chain_EndsoftheEarth = "endsoftheearthchain", Chain_FairyHarp = "fairyharpchain", Chain_FairyStars = "fairystarschain", Chain_FatalCrest = "fatalcrestchain", Chain_Fenrir = "fenrirchain", Chain_FerrisGear = "ferrisgearchain", Chain_FollowtheWind = "followthewindchain", Chain_FrolicFlame = "frolicflamechain", Chain_GlimpseofDarkness = "glimpseofdarknesschain", Chain_GuardianBell = "guardianbellchain", Chain_GuardianSoul = "guardiansoulchain", Chain_GullWing = "gullwingchain", Chain_HerosCrest = "heroscrestchain", Chain_HiddenDragon = "hiddendragonchain", Chain_Hyperdrive = "hyperdrivechain", Chain_IncompleteKiblade = "incompletekibladechain", Chain_JungleKing = "junglekingchain", Chain_KeybladeofPeoplesHearts = "keybladeofpeoplesheartschain", Chain_Kiblade = "kibladechain", Chain_KingdomKey = "kingdomkeychain", Chain_KingdomKeyD = "kingdomkeydchain", Chain_KnockoutPunch = "knockoutpunchchain", Chain_LadyLuck = "ladyluckchain",
			Chain_LeasKeyblade = "leaskeybladechain", Chain_LeopardosForetellersKeyblade = "leopardosforetellerskeybladechain", Chain_Leviathan = "leviathanchain", Chain_Lionheart = "lionheartchain", Chain_LostMemory = "lostmemorychain", Chain_LunarEclipse = "lunareclipsechain", Chain_MarkofaHero = "markofaherochain", Chain_MasterXehanortsKeyblade = "masterxehanortskeybladechain", Chain_MastersDefender = "mastersdefenderchain", Chain_MaverickFlare = "maverickflarechain", Chain_MetalChocobo = "metalchocobochain", Chain_MidnightRoar = "midnightroarchain", Chain_MirageSplit = "miragesplitchain", Chain_MissingAche = "missingachechain", Chain_Monochrome = "monochromechain", Chain_MysteriousAbyss = "mysteriousabysschain", Chain_NightmaresEnd = "nightmaresendchain", Chain_NightmaresEndandMirageSplit = "nightmaresendandmiragesplitchain", Chain_NoName = "nonamechain", Chain_Oathkeeper = "oathkeeperchain", Chain_Oblivion = "oblivionchain", Chain_OceansRage = "oceansragechain",
			Chain_Olympia = "olympiachain", Chain_OmegaWeapon = "omegaweaponchain", Chain_OminousBlight = "ominousblightchain", Chain_OneWingedAngel = "onewingedangelchain", Chain_PainofSolitude = "painofsolitudechain", Chain_PhotonDebugger = "photondebuggerchain", Chain_PixiePetal = "pixiepetalchain", Chain_Pumpkinhead = "pumpkinheadchain", Chain_Rainfell = "rainfellchain", Chain_RejectionofFate = "rejectionoffatechain", Chain_RoyalRadiance = "royalradiancechain", Chain_RumblingRose = "rumblingrosechain", Chain_SignofInnocence = "signofinnocencechain", Chain_SilentDirge = "silentdirgechain", Chain_SkullNoise = "skullnoisechain", Chain_SleepingLion = "sleepinglionchain", Chain_SoulEater = "souleaterchain", Chain_Spellbinder = "spellbinderchain", Chain_StarSeeker = "starseekerchain", Chain_Starlight = "starlightchain", Chain_Stormfall = "stormfallchain", Chain_StrokeofMidnight = "strokeofmidnightchain", Chain_SweetDreams = "sweetdreamschain", Chain_SweetMemories = "sweetmemorieschain",
			Chain_Sweetstack = "sweetstackchain", Chain_ThreeWishes = "threewisheschain", Chain_TotalEclipse = "totaleclipsechain", Chain_TreasureTrove = "treasuretrovechain", Chain_TrueLightsFlight = "truelightsflightchain", Chain_TwilightBlaze = "twilightblazechain", Chain_TwoBecomeOne = "twobecomeonechain", Chain_UltimaWeaponKH1 = "ultimaweaponkh1chain", Chain_UltimaWeaponKH2 = "ultimaweaponkh2chain", Chain_UltimaWeaponBBS = "ultimaweaponbbschain", Chain_UltimaWeaponDDD = "ultimaweapondddchain", Chain_Umbrella = "umbrellachain", Chain_Unbound = "unboundchain", Chain_UnicornisForetellersKeyblade = "unicornisforetellerskeybladechain", Chain_UrsusForetellersKeyblade = "ursusforetellerskeybladechain", Chain_VictoryLine = "victorylinechain", Chain_VoidGear = "voidgearchain", Chain_VulpeusForetellersKeyblade = "vulpeusforetellerskeybladechain", Chain_WaytotheDawn = "waytothedawnchain", Chain_WaywardWind = "waywardwindchain", Chain_WinnersProof = "winnersproofchain",
			Chain_WishingLamp = "wishinglampchain", Chain_WishingStar = "wishingstarchain", Chain_WoodenKeyblade = "woodenkeybladechain", Chain_WoodenStick = "woodenstickchain", Chain_YoungXehanortsKeyblade = "youngxehanortskeybladechain", Chain_ZeroOne = "zeroonechain";

	// Config

	// Materials
	public static final String TM_Interdiction_DEFAULT = "interdiction, 3, -1, 6.0F, 10, 30", TM_Sharpshooter_DEFAULT = "sharpshooter, 3, -1, 6.0F, 4, 30", TM_Lindworm_DEFAULT = "lindworm, 3, -1, 6.0F, 9, 30", TM_FrozenPride_DEFAULT = "frozenpride, 3, -1, 6.0F, 6, 30", TM_Skysplitter_DEFAULT = "skysplitter, 3, -1, 6.0F, 20, 30", TM_BookofRetribution_DEFAULT = "bookofretribution, 3, -1, 6.0F, 5, 30", TM_Lunatic_DEFAULT = "lunatic, 3, -1, 6.0F, 15, 30", TM_EternalFlames_DEFAULT = "eternalflames, 3, -1, 6.0F, 5, 30", TM_Arpeggio_DEFAULT = "arpeggio, 3, -1, 6.0F, 9, 30", TM_FairGame_DEFAULT = "fairgame, 3, -1, 6.0F, 8, 30", TM_GracefulDahlia_DEFAULT = "gracefuldahlia, 3, -1, 6.0F, 12, 30", TM_Foudre_DEFAULT = "foudre, 3, -1, 6.0F, 7, 30", TM_BlazeofGlory_DEFAULT = "eternalflames, 3, -1, 6.0F, 5, 30", TM_Prometheus_DEFAULT = "prometheus, 3, -1, 6.0F, 5, 30", TM_Ifrit_DEFAULT = "ifrit, 3, -1, 6.0F, 5, 30";

	public static final String TM_KingdomKey_DEFAULT = "kingdomkey, 3, -1, 6.0F, 5, 30", TM_Oathkeeper_DEFAULT = "oathkeeper, 3, -1, 6.0F, 11, 30", TM_Oblivion_DEFAULT = "oblivion, 3, -1, 6.0F, 13, 30", TM_UltimaWeaponKH1_DEFAULT = "ultimaweaponkh1, 3, -1, 6.0F, 18, 30", TM_KingdomKeyD_DEFAULT = "kingdomkeyd, 3, -1, 6.0F, 5, 30", TM_KeybladeofPeoplesHearts_DEFAULT = "keybladeofpeopleshearts, 3, -1, 6.0F, 13, 30", TM_LadyLuck_DEFAULT = "ladyluck, 3, -1, 6.0F, 6, 30", TM_Olympia_DEFAULT = "olympia, 3, -1, 6.0F, 9, 30", TM_JungleKing_DEFAULT = "jungleking, 3, -1, 6.0F, 7, 30", TM_ThreeWishes_DEFAULT = "threewishes, 3, -1, 6.0F, 8, 30", TM_Crabclaw_DEFAULT = "crabclaw, 3, -1, 6.0F, 5, 30", TM_FairyHarp_DEFAULT = "fairyharp, 3, -1, 6.0F, 7, 30", TM_DivineRose_DEFAULT = "divinerose, 3, -1, 6.0F, 6, 30", TM_Spellbinder_DEFAULT = "spellbinder, 3, -1, 6.0F, 6, 30", TM_MetalChocobo_DEFAULT = "metalchocobo, 3, -1, 6.0F, 7, 30", TM_Lionheart_DEFAULT = "lionheart, 3, -1, 6.0F, 7, 30",
			TM_DiamondDust_DEFAULT = "diamonddust, 3, -1, 6.0F, 10, 30", TM_OneWingedAngel_DEFAULT = "onewingedangel, 3, -1, 6.0F, 15, 30", TM_SoulEater_DEFAULT = "souleater, 3, -1, 6.0F, 12, 30", TM_Pumpkinhead_DEFAULT = "pumpkinhead, 3, -1, 6.0F, 10, 30", TM_WishingStar_DEFAULT = "wishingstar, 3, -1, 6.0F, 9, 30", TM_BondofFlame_DEFAULT = "bondofflame, 3, -1, 6.0F, 14, 30", TM_FollowtheWind_DEFAULT = "followthewind, 3, -1, 6.0F, 8, 30", TM_HiddenDragon_DEFAULT = "hiddendragon, 3, -1, 6.0F, 7, 30", TM_Monochrome_DEFAULT = "monochrome, 3, -1, 6.0F, 6, 30", TM_PhotonDebugger_DEFAULT = "photondebugger, 3, -1, 6.0F, 6, 30", TM_StarSeeker_DEFAULT = "starseeker, 3, -1, 6.0F, 12, 30", TM_MaverickFlare_DEFAULT = "maverickflare, 3, -1, 6.0F, 9, 30", TM_TotalEclipse_DEFAULT = "totaleclipse, 3, -1, 6.0F, 9, 30", TM_MidnightRoar_DEFAULT = "midnightroar, 3, -1, 6.0F, 11, 30", TM_TwoBecomeOne_DEFAULT = "twobecomeone, 3, -1, 6.0F, 20, 30",
			TM_UltimaWeaponKH2_DEFAULT = "ultimaweaponkh2, 3, -1, 6.0F, 18, 30", TM_WaytotheDawn_DEFAULT = "waytothedawn, 3, -1, 6.0F, 9, 30", TM_DestinysEmbrace_DEFAULT = "destinysembrace, 3, -1, 6.0F, 7, 30", TM_Stormfall_DEFAULT = "stormfall, 3, -1, 6.0F, 8, 30", TM_EndsoftheEarth_DEFAULT = "endsoftheearth, 3, -1, 6.0F, 9, 30", TM_RumblingRose_DEFAULT = "rumblingrose, 3, -1, 6.0F, 11, 30", TM_HerosCrest_DEFAULT = "heroscrest, 3, -1, 6.0F, 6, 30", TM_MysteriousAbyss_DEFAULT = "mysteriousabyss, 3, -1, 6.0F, 6, 30", TM_WishingLamp_DEFAULT = "wishinglamp, 3, -1, 6.0F, 7, 30", TM_DecisivePumpkin_DEFAULT = "decisivepumpkin, 3, -1, 6.0F, 21, 30", TM_CircleofLife_DEFAULT = "circleoflife, 3, -1, 6.0F, 9, 30", TM_SweetMemories_DEFAULT = "sweetmemories, 3, -1, 6.0F, 7, 30", TM_GullWing_DEFAULT = "gullwing, 3, -1, 6.0F, 5, 30", TM_GuardianSoul_DEFAULT = "guardiansoul, 3, -1, 6.0F, 8, 30", TM_SleepingLion_DEFAULT = "sleepinglion, 3, -1, 6.0F, 13, 30",
			TM_Fenrir_DEFAULT = "fenrir, 3, -1, 6.0F, 24, 30", TM_FatalCrest_DEFAULT = "fatalcrest, 3, -1, 6.0F, 17, 30", TM_WinnersProof_DEFAULT = "winnersproof, 3, -1, 6.0F, 12, 30", TM_MissingAche_DEFAULT = "missingache, 3, -1, 6.0F, 8, 30", TM_OminousBlight_DEFAULT = "ominousblight, 3, -1, 6.0F, 10, 30", TM_AbaddonPlasma_DEFAULT = "abaddonplasma, 3, -1, 6.0F, 7, 30", TM_PainofSolitude_DEFAULT = "painofsolitude, 3, -1, 6.0F, 5, 30", TM_SignofInnocence_DEFAULT = "signofinnocence, 3, -1, 6.0F, 6, 30", TM_CrownofGuilt_DEFAULT = "crownofguilt, 3, -1, 6.0F, 9, 30", TM_AbyssalTide_DEFAULT = "abyssaltide, 3, -1, 6.0F, 7, 30", TM_Leviathan_DEFAULT = "leviathan, 3, -1, 6.0F, 9, 30", TM_TrueLightsFlight_DEFAULT = "truelightsflight, 3, -1, 6.0F, 8, 30", TM_RejectionofFate_DEFAULT = "rejectionoffate, 3, -1, 6.0F, 8, 30", TM_GlimpseofDarkness_DEFAULT = "glimpseofdarkness, 3, -1, 6.0F, 6, 30", TM_SilentDirge_DEFAULT = "silentdirge, 3, -1, 6.0F, 7, 30",
			TM_LunarEclipse_DEFAULT = "lunareclipse, 3, -1, 6.0F, 6, 30", TM_DarkerThanDark_DEFAULT = "darkerthandark, 3, -1, 6.0F, 8, 30", TM_AstralBlast_DEFAULT = "astralblast, 3, -1, 6.0F, 9, 30", TM_TwilightBlaze_DEFAULT = "twilightblaze, 3, -1, 6.0F, 11, 30", TM_OmegaWeapon_DEFAULT = "omegaweapon, 3, -1, 6.0F, 13, 30", TM_Umbrella_DEFAULT = "umbrella, 3, -1, 6.0F, 4, 30", TM_Aubade_DEFAULT = "aubade, 3, -1, 6.0F, 9, 30", TM_WoodenStick_DEFAULT = "woodenstick, 3, -1, 6.0F, -4, 30", TM_DreamSword_DEFAULT = "dreamsword, 3, -1, 6.0F, 5, 30", TM_ZeroOne_DEFAULT = "zeroone, 3, -1, 6.0F, 12, 30", TM_Earthshaker_DEFAULT = "earthshaker, 3, -1, 6.0F, 10, 30", TM_Darkgnaw_DEFAULT = "darkgnaw, 3, -1, 6.0F, 10, 30", TM_ChaosRipper_DEFAULT = "chaosripper, 3, -1, 6.0F, 7, 30", TM_MasterXehanortsKeyblade_DEFAULT = "masterxehanortskeyblade, 3, -1, 6.0F, 18, 30", TM_TreasureTrove_DEFAULT = "treasuretrove, 3, -1, 6.0F, 7, 30", TM_StrokeofMidnight_DEFAULT = "strokeofmidnight, 3, -1, 6.0F, 6, 30",
			TM_FairyStars_DEFAULT = "fairystars, 3, -1, 6.0F, 6, 30", TM_VictoryLine_DEFAULT = "victoryline, 3, -1, 6.0F, 7, 30", TM_MarkofaHero_DEFAULT = "markofahero, 3, -1, 6.0F, 7, 30", TM_Hyperdrive_DEFAULT = "hyperdrive, 3, -1, 6.0F, 8, 30", TM_PixiePetal_DEFAULT = "pixiepetal, 3, -1, 6.0F, 6, 30", TM_Sweetstack_DEFAULT = "sweetstack, 3, -1, 6.0F, 8, 30", TM_UltimaWeaponBBS_DEFAULT = "ultimaweaponbbs, 3, -1, 6.0F, 18, 30", TM_VoidGear_DEFAULT = "voidgear, 3, -1, 6.0F, 11, 30", TM_NoName_DEFAULT = "noname, 3, -1, 6.0F, 12, 30", TM_RoyalRadiance_DEFAULT = "royalradiance, 3, -1, 6.0F, 10, 30", TM_Rainfell_DEFAULT = "rainfell, 3, -1, 6.0F, 6, 30", TM_Brightcrest_DEFAULT = "brightcrest, 3, -1, 6.0F, 7, 30", TM_MastersDefender_DEFAULT = "mastersdefender, 3, -1, 6.0F, 13, 30", TM_WaywardWind_DEFAULT = "waywardwind, 3, -1, 6.0F, 8, 30", TM_FrolicFlame_DEFAULT = "frolicflame, 3, -1, 6.0F, 6, 30", TM_LostMemory_DEFAULT = "lostmemory, 3, -1, 6.0F, 12, 30",
			TM_Kiblade_DEFAULT = "kiblade, 3, -1, 6.0F, 25, 30", TM_IncompleteKiblade_DEFAULT = "incompletekiblade, 3, -1, 6.0F, 13, 30", TM_WoodenKeyblade_DEFAULT = "woodenkeyblade, 3, -1, 6.0F, 2, 30", TM_SkullNoise_DEFAULT = "skullnoise, 3, -1, 6.0F, 6, 30", TM_GuardianBell_DEFAULT = "guardianbell, 3, -1, 6.0F, 7, 30", TM_DualDisc_DEFAULT = "dualdisc, 3, -1, 6.0F, 7, 30", TM_FerrisGear_DEFAULT = "ferrisgear, 3, -1, 6.0F, 6, 30", TM_KnockoutPunch_DEFAULT = "knockoutpunch, 3, -1, 6.0F, 5, 30", TM_AllforOne_DEFAULT = "allforone, 3, -1, 6.0F, 5, 30", TM_Counterpoint_DEFAULT = "counterpoint, 3, -1, 6.0F, 7, 30", TM_Divewing_DEFAULT = "divewing, 3, -1, 6.0F, 7, 30", TM_SweetDreams_DEFAULT = "sweetdreams, 3, -1, 6.0F, 9, 30", TM_UltimaWeaponDDD_DEFAULT = "ultimaweaponddd, 3, -1, 6.0F, 18, 30", TM_Unbound_DEFAULT = "unbound, 3, -1, 6.0F, 13, 30", TM_EndofPain_DEFAULT = "endofpain, 3, -1, 6.0F, 9, 30", TM_OceansRage_DEFAULT = "oceansrage, 3, -1, 6.0F, 8, 30",
			TM_LeasKeyblade_DEFAULT = "leaskeyblade, 3, -1, 6.0F, 8, 30", TM_YoungXehanortsKeyblade_DEFAULT = "youngxehanortskeyblade, 3, -1, 6.0F, 15, 30", TM_MirageSplit_DEFAULT = "miragesplit, 3, -1, 6.0F, 16, 30", TM_NightmaresEnd_DEFAULT = "nightmaresend, 3, -1, 6.0F, 16, 30", TM_NightmaresEndandMirageSplit_DEFAULT = "nightmaresendandmiragesplit, 3, -1, 6.0F, 23, 30", TM_Starlight_DEFAULT = "starlight, 3, -1, 6.0F, 6, 30", TM_AnguisForetellersKeyblade_DEFAULT = "anguisforetellerskeyblade, 3, -1, 6.0F, 9, 30", TM_LeopardosForetellersKeyblade_DEFAULT = "leopardosforetellerskeyblade, 3, -1, 6.0F, 17, 30", TM_UnicornisForetellersKeyblade_DEFAULT = "unicornisforetellerskeyblade, 3, -1, 6.0F, 15, 30", TM_UrsusForetellersKeyblade_DEFAULT = "ursusforetellerskeyblade, 3, -1, 6.0F, 18, 30", TM_VulpeusForetellersKeyblade_DEFAULT = "vulpeusforetellerskeyblade, 3, -1, 6.0F, 16, 30";

	// public static String testToolMaterial;

	public static final String TOOLMATERIAL = "toolmaterial.name.";

	public static final String TM_Interdiction_NAME = TOOLMATERIAL + Interdiction, TM_Sharpshooter_NAME = TOOLMATERIAL + Sharpshooter, TM_Lindworm_NAME = TOOLMATERIAL + Lindworm, TM_FrozenPride_NAME = TOOLMATERIAL + FrozenPride, TM_Skysplitter_NAME = TOOLMATERIAL + Skysplitter, TM_BookofRetribution_NAME = TOOLMATERIAL + BookofRetribution, TM_Lunatic_NAME = TOOLMATERIAL + Lunatic, TM_EternalFlames_NAME = TOOLMATERIAL + EternalFlames, TM_Arpeggio_NAME = TOOLMATERIAL + Arpeggio, TM_FairGame_NAME = TOOLMATERIAL + FairGame, TM_GracefulDahlia_NAME = TOOLMATERIAL + GracefulDahlia, TM_Foudre_NAME = TOOLMATERIAL + Foudre, TM_BlazeofGlory_NAME = TOOLMATERIAL + BlazeofGlory, TM_Prometheus_NAME = TOOLMATERIAL + Prometheus, TM_Ifrit_NAME = TOOLMATERIAL + Ifrit;

	public static final String TM_KingdomKey_NAME = TOOLMATERIAL + KingdomKey, TM_Oathkeeper_NAME = TOOLMATERIAL + Oathkeeper, TM_Oblivion_NAME = TOOLMATERIAL + Oblivion, TM_UltimaWeaponKH1_NAME = TOOLMATERIAL + UltimaWeaponKH1, TM_KingdomKeyD_NAME = TOOLMATERIAL + KingdomKeyD, TM_KeybladeofPeoplesHearts_NAME = TOOLMATERIAL + KeybladeofPeoplesHearts, TM_LadyLuck_NAME = TOOLMATERIAL + LadyLuck, TM_Olympia_NAME = TOOLMATERIAL + Olympia, TM_JungleKing_NAME = TOOLMATERIAL + JungleKing, TM_ThreeWishes_NAME = TOOLMATERIAL + ThreeWishes, TM_Crabclaw_NAME = TOOLMATERIAL + Crabclaw, TM_FairyHarp_NAME = TOOLMATERIAL + FairyHarp, TM_DivineRose_NAME = TOOLMATERIAL + DivineRose, TM_Spellbinder_NAME = TOOLMATERIAL + Spellbinder, TM_MetalChocobo_NAME = TOOLMATERIAL + MetalChocobo, TM_Lionheart_NAME = TOOLMATERIAL + Lionheart, TM_DiamondDust_NAME = TOOLMATERIAL + DiamondDust, TM_OneWingedAngel_NAME = TOOLMATERIAL + OneWingedAngel, TM_SoulEater_NAME = TOOLMATERIAL + SoulEater,
			TM_Pumpkinhead_NAME = TOOLMATERIAL + Pumpkinhead, TM_WishingStar_NAME = TOOLMATERIAL + WishingStar, TM_BondofFlame_NAME = TOOLMATERIAL + BondofFlame, TM_FollowtheWind_NAME = TOOLMATERIAL + FollowtheWind, TM_HiddenDragon_NAME = TOOLMATERIAL + HiddenDragon, TM_Monochrome_NAME = TOOLMATERIAL + Monochrome, TM_PhotonDebugger_NAME = TOOLMATERIAL + PhotonDebugger, TM_StarSeeker_NAME = TOOLMATERIAL + StarSeeker, TM_MaverickFlare_NAME = TOOLMATERIAL + MaverickFlare, TM_TotalEclipse_NAME = TOOLMATERIAL + TotalEclipse, TM_MidnightRoar_NAME = TOOLMATERIAL + MidnightRoar, TM_TwoBecomeOne_NAME = TOOLMATERIAL + TwoBecomeOne, TM_UltimaWeaponKH2_NAME = TOOLMATERIAL + UltimaWeaponKH2, TM_WaytotheDawn_NAME = TOOLMATERIAL + WaytotheDawn, TM_DestinysEmbrace_NAME = TOOLMATERIAL + DestinysEmbrace, TM_Stormfall_NAME = TOOLMATERIAL + Stormfall, TM_EndsoftheEarth_NAME = TOOLMATERIAL + EndsoftheEarth, TM_RumblingRose_NAME = TOOLMATERIAL + RumblingRose, TM_HerosCrest_NAME = TOOLMATERIAL + HerosCrest,
			TM_MysteriousAbyss_NAME = TOOLMATERIAL + MysteriousAbyss, TM_WishingLamp_NAME = TOOLMATERIAL + WishingLamp, TM_DecisivePumpkin_NAME = TOOLMATERIAL + DecisivePumpkin, TM_CircleofLife_NAME = TOOLMATERIAL + CircleofLife, TM_SweetMemories_NAME = TOOLMATERIAL + SweetMemories, TM_GullWing_NAME = TOOLMATERIAL + GullWing, TM_GuardianSoul_NAME = TOOLMATERIAL + GuardianSoul, TM_SleepingLion_NAME = TOOLMATERIAL + SleepingLion, TM_Fenrir_NAME = TOOLMATERIAL + Fenrir, TM_FatalCrest_NAME = TOOLMATERIAL + FatalCrest, TM_WinnersProof_NAME = TOOLMATERIAL + WinnersProof, TM_MissingAche_NAME = TOOLMATERIAL + MissingAche, TM_OminousBlight_NAME = TOOLMATERIAL + OminousBlight, TM_AbaddonPlasma_NAME = TOOLMATERIAL + AbaddonPlasma, TM_PainofSolitude_NAME = TOOLMATERIAL + PainofSolitude, TM_SignofInnocence_NAME = TOOLMATERIAL + SignofInnocence, TM_CrownofGuilt_NAME = TOOLMATERIAL + CrownofGuilt, TM_AbyssalTide_NAME = TOOLMATERIAL + AbyssalTide, TM_Leviathan_NAME = TOOLMATERIAL + Leviathan,
			TM_TrueLightsFlight_NAME = TOOLMATERIAL + TrueLightsFlight, TM_RejectionofFate_NAME = TOOLMATERIAL + RejectionofFate, TM_GlimpseofDarkness_NAME = TOOLMATERIAL + GlimpseofDarkness, TM_SilentDirge_NAME = TOOLMATERIAL + SilentDirge, TM_LunarEclipse_NAME = TOOLMATERIAL + LunarEclipse, TM_DarkerThanDark_NAME = TOOLMATERIAL + DarkerThanDark, TM_AstralBlast_NAME = TOOLMATERIAL + AstralBlast, TM_TwilightBlaze_NAME = TOOLMATERIAL + TwilightBlaze, TM_OmegaWeapon_NAME = TOOLMATERIAL + OmegaWeapon, TM_Umbrella_NAME = TOOLMATERIAL + Umbrella, TM_Aubade_NAME = TOOLMATERIAL + Aubade, TM_WoodenStick_NAME = TOOLMATERIAL + WoodenStick, TM_DreamSword_NAME = TOOLMATERIAL + DreamSword, TM_ZeroOne_NAME = TOOLMATERIAL + ZeroOne, TM_Earthshaker_NAME = TOOLMATERIAL + Earthshaker, TM_Darkgnaw_NAME = TOOLMATERIAL + Darkgnaw, TM_ChaosRipper_NAME = TOOLMATERIAL + ChaosRipper, TM_MasterXehanortsKeyblade_NAME = TOOLMATERIAL + MasterXehanortsKeyblade, TM_TreasureTrove_NAME = TOOLMATERIAL + TreasureTrove,
			TM_StrokeofMidnight_NAME = TOOLMATERIAL + StrokeofMidnight, TM_FairyStars_NAME = TOOLMATERIAL + FairyStars, TM_VictoryLine_NAME = TOOLMATERIAL + VictoryLine, TM_MarkofaHero_NAME = TOOLMATERIAL + MarkofaHero, TM_Hyperdrive_NAME = TOOLMATERIAL + Hyperdrive, TM_PixiePetal_NAME = TOOLMATERIAL + PixiePetal, TM_Sweetstack_NAME = TOOLMATERIAL + Sweetstack, TM_UltimaWeaponBBS_NAME = TOOLMATERIAL + UltimaWeaponBBS, TM_VoidGear_NAME = TOOLMATERIAL + VoidGear, TM_NoName_NAME = TOOLMATERIAL + NoName, TM_RoyalRadiance_NAME = TOOLMATERIAL + RoyalRadiance, TM_Rainfell_NAME = TOOLMATERIAL + Rainfell, TM_Brightcrest_NAME = TOOLMATERIAL + Brightcrest, TM_MastersDefender_NAME = TOOLMATERIAL + MastersDefender, TM_WaywardWind_NAME = TOOLMATERIAL + WaywardWind, TM_FrolicFlame_NAME = TOOLMATERIAL + FrolicFlame, TM_LostMemory_NAME = TOOLMATERIAL + LostMemory, TM_Kiblade_NAME = TOOLMATERIAL + Kiblade, TM_IncompleteKiblade_NAME = TOOLMATERIAL + IncompleteKiblade,
			TM_WoodenKeyblade_NAME = TOOLMATERIAL + WoodenKeyblade, TM_SkullNoise_NAME = TOOLMATERIAL + SkullNoise, TM_GuardianBell_NAME = TOOLMATERIAL + GuardianBell, TM_DualDisc_NAME = TOOLMATERIAL + DualDisc, TM_FerrisGear_NAME = TOOLMATERIAL + FerrisGear, TM_KnockoutPunch_NAME = TOOLMATERIAL + KnockoutPunch, TM_AllforOne_NAME = TOOLMATERIAL + AllforOne, TM_Counterpoint_NAME = TOOLMATERIAL + Counterpoint, TM_Divewing_NAME = TOOLMATERIAL + Divewing, TM_SweetDreams_NAME = TOOLMATERIAL + SweetDreams, TM_UltimaWeaponDDD_NAME = TOOLMATERIAL + UltimaWeaponDDD, TM_Unbound_NAME = TOOLMATERIAL + Unbound, TM_EndofPain_NAME = TOOLMATERIAL + EndofPain, TM_OceansRage_NAME = TOOLMATERIAL + OceansRage, TM_LeasKeyblade_NAME = TOOLMATERIAL + LeasKeyblade, TM_YoungXehanortsKeyblade_NAME = TOOLMATERIAL + YoungXehanortsKeyblade, TM_MirageSplit_NAME = TOOLMATERIAL + MirageSplit, TM_NightmaresEnd_NAME = TOOLMATERIAL + NightmaresEnd, TM_NightmaresEndandMirageSplit_NAME = TOOLMATERIAL
					+ NightmaresEndandMirageSplit, TM_Starlight_NAME = TOOLMATERIAL + Starlight, TM_AnguisForetellersKeyblade_NAME = TOOLMATERIAL + AnguisForetellersKeyblade, TM_LeopardosForetellersKeyblade_NAME = TOOLMATERIAL + LeopardosForetellersKeyblade, TM_UnicornisForetellersKeyblade_NAME = TOOLMATERIAL + UnicornisForetellersKeyblade, TM_UrsusForetellersKeyblade_NAME = TOOLMATERIAL + UrsusForetellersKeyblade, TM_VulpeusForetellersKeyblade_NAME = TOOLMATERIAL + VulpeusForetellersKeyblade;
	public static final String KeychainInventory = "container.keychain", SynthBagInventory = "container.synthbag", SynthesisBagSInventory = "container.synthesisbagsinventory", SynthesisBagMInventory = "container.synthesisbagminventory", SynthesisBagLInventory = "container.synthesisbaglinventory";

	// Keyblades
}
