package uk.co.wehavecookies56.kk.common.lib;

import static uk.co.wehavecookies56.kk.common.item.ModItems.*;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.item.Item;
import uk.co.wehavecookies56.kk.common.core.handler.MainConfig;
import uk.co.wehavecookies56.kk.common.util.Utils;

public class Lists {

    public static List<String> recipes = new ArrayList<String>();

    public static List<Item> Xemnas = new ArrayList<Item>();
    public static List<Item> Xigbar = new ArrayList<Item>();
    public static List<Item> Xaldin = new ArrayList<Item>();
    public static List<Item> Vexen = new ArrayList<Item>();
    public static List<Item> Lexaeus = new ArrayList<Item>();
    public static List<Item> Zexion = new ArrayList<Item>();
    public static List<Item> Saix = new ArrayList<Item>();
    public static List<Item> Axel = new ArrayList<Item>();
    public static List<Item> Demyx = new ArrayList<Item>();
    public static List<Item> Luxord = new ArrayList<Item>();
    public static List<Item> Marluxia = new ArrayList<Item>();
    public static List<Item> Larxene = new ArrayList<Item>();
    public static List<Item> Roxas = new ArrayList<>();

    public static List<Item> getListForMember(Utils.OrgMember member) {
        switch (member) {
            case AXEL: return Axel;
            case DEMYX: return Demyx;
            case LARXENE: return Larxene;
            case LEXAEUS: return Lexaeus;
            case LUXORD: return Luxord;
            case MARLUXIA: return Marluxia;
            case ROXAS: return Roxas;
            case SAIX: return Saix;
            case VEXEN: return Vexen;
            case XALDIN: return Xaldin;
            case XEMNAS: return Xemnas;
            case XIGBAR: return Xigbar;
            case ZEXION: return Zexion;
            case NONE: return null;
        }
        return null;
    }

    public static void init () {

        //Xemnas
        Xemnas.add(Malice);
        Xemnas.add(Sanction);
        Xemnas.add(Overlord);
        Xemnas.add(Veneration);
        Xemnas.add(Autocracy);
        Xemnas.add(Conquest);
        Xemnas.add(Terminus);
        Xemnas.add(Judgement);
        Xemnas.add(Discipline);
        Xemnas.add(Aristocracy);
        Xemnas.add(Superiority);
        Xemnas.add(Aggression);
        Xemnas.add(Fury);
        Xemnas.add(Despair);
        Xemnas.add(Triumph);
        Xemnas.add(Ruination);
        Xemnas.add(Domination);
        Xemnas.add(Annihilation);
        Xemnas.add(Tyrant);
        Xemnas.add(Magnificence);
        Xemnas.add(Infinity);
        Xemnas.add(Interdiction);
        Xemnas.add(RoundFan);
        Xemnas.add(Absolute);

        //Xigbar
        Xigbar.add(Standalone);
        Xigbar.add(Killerbee);
        Xigbar.add(Stingray);
        Xigbar.add(Counterweight);
        Xigbar.add(Precision);
        Xigbar.add(DualHead);
        Xigbar.add(Bahamut);
        Xigbar.add(Gullwing);
        Xigbar.add(BlueFrame);
        Xigbar.add(StarShell);
        Xigbar.add(Sunrise);
        Xigbar.add(Ignition);
        Xigbar.add(Armstrong);
        Xigbar.add(HardBoiledHeat);
        Xigbar.add(DiabloEye);
        Xigbar.add(DoubleTap);
        Xigbar.add(Stardust);
        Xigbar.add(EnergyMuzzle);
        Xigbar.add(CrimeAndPunishment);
        Xigbar.add(CupidsArrow);
        Xigbar.add(FinalWeapon);
        Xigbar.add(Sharpshooter);
        Xigbar.add(Dryer);
        Xigbar.add(Trumpet);

        //Xaldin
        Xaldin.add(Zephyr);
        Xaldin.add(Moonglade);
        Xaldin.add(Aer);
        Xaldin.add(Nescience);
        Xaldin.add(Brume);
        Xaldin.add(Asura);
        Xaldin.add(Crux);
        Xaldin.add(Paladin);
        Xaldin.add(Fellking);
        Xaldin.add(Nightcloud);
        Xaldin.add(Shimmer);
        Xaldin.add(Vortex);
        Xaldin.add(Scission);
        Xaldin.add(Heavenfall);
        Xaldin.add(Aether);
        Xaldin.add(Mazzaroth);
        Xaldin.add(Hegemon);
        Xaldin.add(Foxfire);
        Xaldin.add(Yaksha);
        Xaldin.add(Cynosura);
        Xaldin.add(Dragonreign);
        Xaldin.add(Lindworm);
        Xaldin.add(Broom);
        Xaldin.add(Wyvern);

        //Vexen
        Vexen.add(TesterZero);
        Vexen.add(ProductOne);
        Vexen.add(DeepFreeze);
        Vexen.add(CryoliteShield);
        Vexen.add(FalseTheory);
        Vexen.add(Glacier);
        Vexen.add(AbsoluteZero);
        Vexen.add(Gunz);
        Vexen.add(Mindel);
        Vexen.add(Snowslide);
        Vexen.add(Iceberg);
        Vexen.add(Inquisition);
        Vexen.add(Scrutiny);
        Vexen.add(Empiricism);
        Vexen.add(Edification);
        Vexen.add(Contrivance);
        Vexen.add(Wurm);
        Vexen.add(Subzero);
        Vexen.add(ColdBlood);
        Vexen.add(DiamondShield);
        Vexen.add(Aegis);
        Vexen.add(FrozenPride);
        Vexen.add(PotLid);
        Vexen.add(Snowman);

        //Lexaeus
        Lexaeus.add(Reticence);
        Lexaeus.add(Goliath);
        Lexaeus.add(CopperRed);
        Lexaeus.add(Daybreak);
        Lexaeus.add(Colossus);
        Lexaeus.add(UrsaMajor);
        Lexaeus.add(Megacosm);
        Lexaeus.add(Terrene);
        Lexaeus.add(Fuligin);
        Lexaeus.add(HardWinter);
        Lexaeus.add(Firefly);
        Lexaeus.add(Harbinger);
        Lexaeus.add(Redwood);
        Lexaeus.add(Sequoia);
        Lexaeus.add(IronBlack);
        Lexaeus.add(Earthshine);
        Lexaeus.add(Octiron);
        Lexaeus.add(Hyperion);
        Lexaeus.add(Clarity);
        Lexaeus.add(OneThousandAndOneNights);
        Lexaeus.add(CardinalVirtue);
        Lexaeus.add(Skysplitter);
        Lexaeus.add(BleepBloopBop);
        Lexaeus.add(Monolith);

        //Zexion
        Zexion.add(BlackPrimer);
        Zexion.add(WhiteTome);
        Zexion.add(IllicitResearch);
        Zexion.add(BuriedSecrets);
        Zexion.add(ArcaneCompendium);
        Zexion.add(DissentersNotes);
        Zexion.add(NefariousCodex);
        Zexion.add(MysticAlbum);
        Zexion.add(CursedManual);
        Zexion.add(TabooText);
        Zexion.add(EldritchEsoterica);
        Zexion.add(FreakishBestiary);
        Zexion.add(MadmansVita);
        Zexion.add(UntitledWritings);
        Zexion.add(AbandonedDogma);
        Zexion.add(AtlasOfOmens);
        Zexion.add(RevoltingScrapbook);
        Zexion.add(LostHeterodoxy);
        Zexion.add(OtherworldlyTales);
        Zexion.add(IndescribableLore);
        Zexion.add(RadicalTreatise);
        Zexion.add(BookofRetribution);
        Zexion.add(MidnightSnack);
        Zexion.add(DearDiary);

        //Saix
        Saix.add(NewMoon);
        Saix.add(Werewolf);
        Saix.add(Artemis);
        Saix.add(Luminary);
        Saix.add(Selene);
        Saix.add(Moonrise);
        Saix.add(Astrologia);
        Saix.add(Crater);
        Saix.add(LunarPhase);
        Saix.add(Crescent);
        Saix.add(Gibbous);
        Saix.add(Berserker);
        Saix.add(Twilight);
        Saix.add(QueenOfTheNight);
        Saix.add(BalsamicMoon);
        Saix.add(Orbit);
        Saix.add(LightYear);
        Saix.add(KingOfTheNight);
        Saix.add(Moonset);
        Saix.add(Horoscope);
        Saix.add(Dichotomy);
        Saix.add(Lunatic);
        Saix.add(JustDesserts);
        Saix.add(Bunnymoon);

        //Axel
        Axel.add(Ashes);
        Axel.add(Doldrums);
        Axel.add(DelayedAction);
        Axel.add(DiveBombers);
        Axel.add(Combustion);
        Axel.add(MoulinRouge);
        Axel.add(BlazeofGlory);
        Axel.add(Prometheus);
        Axel.add(Ifrit);
        Axel.add(MagmaOcean);
        Axel.add(Volcanics);
        Axel.add(Inferno);
        Axel.add(SizzlingEdge);
        Axel.add(Corona);
        Axel.add(FerrisWheel);
        Axel.add(Burnout);
        Axel.add(OmegaTrinity);
        Axel.add(Outbreak);
        Axel.add(DoubleEdge);
        Axel.add(Wildfire);
        Axel.add(Prominence);
        Axel.add(EternalFlames);
        Axel.add(PizzaCut);
        Axel.add(Conformers);

        //Demyx
        Demyx.add(BasicModel);
        Demyx.add(TuneUp);
        Demyx.add(Quartet);
        Demyx.add(Quintet);
        Demyx.add(Overture);
        Demyx.add(OldHand);
        Demyx.add(DaCapo);
        Demyx.add(PowerChord);
        Demyx.add(Fermata);
        Demyx.add(Interlude);
        Demyx.add(Serenade);
        Demyx.add(Songbird);
        Demyx.add(RiseToFame);
        Demyx.add(RockStar);
        Demyx.add(EightFinger);
        Demyx.add(Concerto);
        Demyx.add(Harmonics);
        Demyx.add(MillionBucks);
        Demyx.add(Fortissimo);
        Demyx.add(UpToEleven);
        Demyx.add(Sanctuary);
        Demyx.add(Arpeggio);
        Demyx.add(PrinceOfAwesome);
        Demyx.add(AfterSchool);

        //Luxord
        Luxord.add(TheFool);
        Luxord.add(TheMagician);
        Luxord.add(TheStar);
        Luxord.add(TheMoon);
        Luxord.add(Justice);
        Luxord.add(TheHierophant);
        Luxord.add(TheWorld);
        Luxord.add(Temperance);
        Luxord.add(TheHighPriestess);
        Luxord.add(TheTower);
        Luxord.add(TheHangedMan);
        Luxord.add(Death);
        Luxord.add(TheHermit);
        Luxord.add(Strength);
        Luxord.add(TheLovers);
        Luxord.add(TheChariot);
        Luxord.add(TheSun);
        Luxord.add(TheDevil);
        Luxord.add(TheEmpress);
        Luxord.add(TheEmperor);
        Luxord.add(TheJoker);
        Luxord.add(FairGame);
        Luxord.add(FinestFantasy13);
        Luxord.add(HighRollersSecret);

        //Marluxia
        Marluxia.add(FickleErica);
        Marluxia.add(JiltedAnemone);
        Marluxia.add(ProudAmaryllis);
        Marluxia.add(MadSafflower);
        Marluxia.add(PoorMelissa);
        Marluxia.add(TragicAllium);
        Marluxia.add(MournfulCineria);
        Marluxia.add(PseudoSilene);
        Marluxia.add(FaithlessDigitalis);
        Marluxia.add(GrimMuscari);
        Marluxia.add(DocileVallota);
        Marluxia.add(QuietBelladonna);
        Marluxia.add(PartingIpheion);
        Marluxia.add(LoftyGerbera);
        Marluxia.add(GallantAchillea);
        Marluxia.add(NoblePeony);
        Marluxia.add(FearsomeAnise);
        Marluxia.add(VindictiveThistle);
        Marluxia.add(FairHelianthus);
        Marluxia.add(SolemnMagnolia);
        Marluxia.add(HallowedLotus);
        Marluxia.add(GracefulDahlia);
        Marluxia.add(StirringLadle);
        Marluxia.add(DaintyBellflowers);

        //Larxene
        Larxene.add(Trancheuse);
        Larxene.add(Orage);
        Larxene.add(Tourbillon);
        Larxene.add(Tempete);
        Larxene.add(Carmin);
        Larxene.add(Meteore);
        Larxene.add(Etoile);
        Larxene.add(Irregulier);
        Larxene.add(Dissonance);
        Larxene.add(Eruption);
        Larxene.add(SoleilCouchant);
        Larxene.add(Indigo);
        Larxene.add(Vague);
        Larxene.add(Deluge);
        Larxene.add(Rafale);
        Larxene.add(Typhon);
        Larxene.add(Extirpeur);
        Larxene.add(CroixDuSud);
        Larxene.add(Lumineuse);
        Larxene.add(ClairdeLune);
        Larxene.add(VoldeNuit);
        Larxene.add(Foudre);
        Larxene.add(Demoiselle);
        Larxene.add(Ampoule);

        Roxas.add(KingdomKey);
        Roxas.add(MissingAche);
        Roxas.add(OminousBlight);
        Roxas.add(AbaddonPlasma);
        Roxas.add(PainofSolitude);
        Roxas.add(SignofInnocence);
        Roxas.add(CrownofGuilt);
        Roxas.add(AbyssalTide);
        Roxas.add(Leviathan);
        Roxas.add(TrueLightsFlight);
        Roxas.add(RejectionofFate);
        Roxas.add(MidnightRoar);
        Roxas.add(GlimpseofDarkness);
        Roxas.add(TotalEclipse);
        Roxas.add(SilentDirge);
        Roxas.add(LunarEclipse);
        Roxas.add(DarkerThanDark);
        Roxas.add(AstralBlast);
        Roxas.add(MaverickFlare);
        Roxas.add(TwilightBlaze);
        Roxas.add(OmegaWeapon);
        Roxas.add(Oathkeeper);
        Roxas.add(TwoBecomeOne);
        Roxas.add(Oblivion);
        Roxas.add(Umbrella);
        Roxas.add(Aubade);
        Roxas.add(WoodenStick);

        //Keyblades
        recipes.add(AbaddonPlasma.getTranslationKey());
        recipes.add(AbyssalTide.getTranslationKey());
        recipes.add(AllforOne.getTranslationKey());
        recipes.add(AnguisForetellersKeyblade.getTranslationKey());
        recipes.add(AstralBlast.getTranslationKey());
        recipes.add(Aubade.getTranslationKey());
        recipes.add(BondofFlame.getTranslationKey());
        recipes.add(Brightcrest.getTranslationKey());
        recipes.add(ChaosRipper.getTranslationKey());
        recipes.add(CircleofLife.getTranslationKey());
        recipes.add(Counterpoint.getTranslationKey());
        recipes.add(Crabclaw.getTranslationKey());
        recipes.add(CrownofGuilt.getTranslationKey());
        recipes.add(DarkerThanDark.getTranslationKey());
        recipes.add(Darkgnaw.getTranslationKey());
        recipes.add(DecisivePumpkin.getTranslationKey());
        recipes.add(DestinysEmbrace.getTranslationKey());
        recipes.add(DiamondDust.getTranslationKey());
        recipes.add(Divewing.getTranslationKey());
        recipes.add(DivineRose.getTranslationKey());
        recipes.add(DreamShield.getTranslationKey());
        recipes.add(DreamStaff.getTranslationKey());
        recipes.add(DreamSword.getTranslationKey());
        recipes.add(DualDisc.getTranslationKey());
        recipes.add(Earthshaker.getTranslationKey());
        recipes.add(EndofPain.getTranslationKey());
        recipes.add(EndsoftheEarth.getTranslationKey());
        recipes.add(FairyHarp.getTranslationKey());
        recipes.add(FairyStars.getTranslationKey());
        recipes.add(FatalCrest.getTranslationKey());
        recipes.add(Fenrir.getTranslationKey());
        recipes.add(FerrisGear.getTranslationKey());
        recipes.add(FollowtheWind.getTranslationKey());
        recipes.add(FrolicFlame.getTranslationKey());
        recipes.add(GlimpseofDarkness.getTranslationKey());
        recipes.add(GuardianBell.getTranslationKey());
        recipes.add(GuardianSoul.getTranslationKey());
        recipes.add(GullWing.getTranslationKey());
        recipes.add(HerosCrest.getTranslationKey());
        recipes.add(HiddenDragon.getTranslationKey());
        recipes.add(Hyperdrive.getTranslationKey());
        recipes.add(IncompleteKiblade.getTranslationKey());
        recipes.add(JungleKing.getTranslationKey());
        recipes.add(KeybladeofPeoplesHearts.getTranslationKey());
        recipes.add(Kiblade.getTranslationKey());
        recipes.add(KingdomKey.getTranslationKey());
        recipes.add(KingdomKeyD.getTranslationKey());
        recipes.add(KnockoutPunch.getTranslationKey());
        recipes.add(LadyLuck.getTranslationKey());
        recipes.add(LeasKeyblade.getTranslationKey());
        recipes.add(LeopardosForetellersKeyblade.getTranslationKey());
        recipes.add(Leviathan.getTranslationKey());
        recipes.add(Lionheart.getTranslationKey());
        recipes.add(LostMemory.getTranslationKey());
        recipes.add(LunarEclipse.getTranslationKey());
        recipes.add(MarkofaHero.getTranslationKey());
        recipes.add(MastersDefender.getTranslationKey());
        recipes.add(MasterXehanortsKeyblade.getTranslationKey());
        recipes.add(MaverickFlare.getTranslationKey());
        recipes.add(MetalChocobo.getTranslationKey());
        recipes.add(MidnightRoar.getTranslationKey());
        recipes.add(MirageSplit.getTranslationKey());
        recipes.add(MissingAche.getTranslationKey());
        recipes.add(Monochrome.getTranslationKey());
        recipes.add(MoogleoGlory.getTranslationKey());
        recipes.add(MysteriousAbyss.getTranslationKey());
        recipes.add(NightmaresEnd.getTranslationKey());
        recipes.add(NightmaresEndandMirageSplit.getTranslationKey());
        recipes.add(NoName.getTranslationKey());
        recipes.add(Oathkeeper.getTranslationKey());
        recipes.add(Oblivion.getTranslationKey());
        recipes.add(OceansRage.getTranslationKey());
        recipes.add(Olympia.getTranslationKey());
        recipes.add(OmegaWeapon.getTranslationKey());
        recipes.add(OminousBlight.getTranslationKey());
        recipes.add(OneWingedAngel.getTranslationKey());
        recipes.add(PainofSolitude.getTranslationKey());
        recipes.add(PhotonDebugger.getTranslationKey());
        recipes.add(PixiePetal.getTranslationKey());
        recipes.add(Pumpkinhead.getTranslationKey());
        recipes.add(Rainfell.getTranslationKey());
        recipes.add(RejectionofFate.getTranslationKey());
        recipes.add(RoyalRadiance.getTranslationKey());
        recipes.add(RumblingRose.getTranslationKey());
        recipes.add(ShootingStar.getTranslationKey());
        recipes.add(SignofInnocence.getTranslationKey());
        recipes.add(SilentDirge.getTranslationKey());
        recipes.add(SkullNoise.getTranslationKey());
        recipes.add(SleepingLion.getTranslationKey());
        recipes.add(SoulEater.getTranslationKey());
        recipes.add(Spellbinder.getTranslationKey());
        recipes.add(Starlight.getTranslationKey());
        recipes.add(StarSeeker.getTranslationKey());
        recipes.add(Stormfall.getTranslationKey());
        recipes.add(StrokeofMidnight.getTranslationKey());
        recipes.add(SweetDreams.getTranslationKey());
        recipes.add(SweetMemories.getTranslationKey());
        recipes.add(Sweetstack.getTranslationKey());
        recipes.add(ThreeWishes.getTranslationKey());
        recipes.add(TotalEclipse.getTranslationKey());
        recipes.add(TreasureTrove.getTranslationKey());
        recipes.add(TrueLightsFlight.getTranslationKey());
        recipes.add(TwilightBlaze.getTranslationKey());
        recipes.add(TwoBecomeOne.getTranslationKey());
        recipes.add(UltimaWeaponBBS.getTranslationKey());
        recipes.add(UltimaWeaponDDD.getTranslationKey());
        recipes.add(UltimaWeaponKH1.getTranslationKey());
        recipes.add(UltimaWeaponKH2.getTranslationKey());
        recipes.add(UltimaWeaponKH3.getTranslationKey());
        recipes.add(Umbrella.getTranslationKey());
        recipes.add(Unbound.getTranslationKey());
        recipes.add(UnicornisForetellersKeyblade.getTranslationKey());
        recipes.add(UrsusForetellersKeyblade.getTranslationKey());
        recipes.add(VictoryLine.getTranslationKey());
        recipes.add(VoidGear.getTranslationKey());
        recipes.add(VulpeusForetellersKeyblade.getTranslationKey());
        recipes.add(WaytotheDawn.getTranslationKey());
        recipes.add(WaywardWind.getTranslationKey());
        recipes.add(WinnersProof.getTranslationKey());
        recipes.add(WishingLamp.getTranslationKey());
        recipes.add(WishingStar.getTranslationKey());
        recipes.add(WoodenKeyblade.getTranslationKey());
        recipes.add(WoodenStick.getTranslationKey());
        recipes.add(YoungXehanortsKeyblade.getTranslationKey());
        recipes.add(ZeroOne.getTranslationKey());
        
        for(String keyblade : MainConfig.items.bannedKeyblades) {
        	if(recipes.indexOf("item."+keyblade) >= 0)
        		recipes.remove(recipes.indexOf("item."+keyblade));
        }
    }

}
