package uk.co.wehavecookies56.kk.common.lib;

public class Strings {

	public static final String tabKingdomKeys = "tabKingdomKeys";
	public static final String tabKingdomKeysBlocks = "tabKingdomKeysblocks";

	// Records
	public static final String
	Disc_Duration_Desc = "disc.duration.desc",
	Disc_DurationUnits_Desc = "disc.durationunits.desc";

	// Choice
	public static final String
	Choice_Sword="sword",
	Choice_Staff="staff",
	Choice_Shield="shield";
	
	// Achievements
	public static final String 
	Achievement_OpenMenu = "achievement.openmenu",
	Achievement_GetKeyblade = "achievement.getkeyblade",
	Achievement_GetWehavecookies56Skull = "achievement.getWehavecookies56Skull",
	Achievement_GetAbelatoxSkull = "achievement.getAbelatoxSkull",
	Achievement_GetBlox = "achievement.getblox",
	Achievement_GetSynthesisTable = "achievement.getSynthesisTable",
	Achievement_GetRecipe = "achievement.getrecipe",
	Achievement_AllRecipes = "achievement.allrecipes",
	Achievement_GetChest = "achievement.getchest",
	Achievement_GetKeybladeArmor = "achievement.getkeybladearmor",
	Achievement_GetOrgWeapon = "achievement.getorgweapon",
	Achievement_GetOrgRobe = "achievement.getorgrobe",
	Achievement_GetKiblade = "achievement.getkiblade",
	Achievement_GetNBMS = "achievement.getnbms",
	Achievement_GetCombined = "achievement.getcombined",
	Achievement_GetIncomepleteKiblade = "achievement.getincompletekiblade",
	Achievement_Get1milMunny = "achievement.get1milmunny",
	Achievement_GetKingdomHearts = "achievement.getkingdomhearts",
	Achievement_GetMagic = "achievement.getmagic",
	Achievement_GetDriveForm = "achievement.getdriveform",
	Achievement_Level100 = "achievement.level100",
	Achievement_Level50 = "achievement.level50",
	Achievement_FreeDev = "achievement.freedev",
	Achievement_GetSynthesisBag = "achievement.getsynthesisbag",
	Achievement_GetPrizeBlox = "achievement.getprizeblox",
	Achievement_PlayMusicDisc = "achievement.playmusicdisc",
	Achievement_GetUltimaWeapon = "achievement.getultimaweapon",
	Achievement_GetStick = "achievement.getstick",
	Achievement_GetUmbrella = "achievement.getumbrella",
	Achievement_GetDreamSword = "achievement.getdreamsword",
	Achievement_GetGhostBlox = "achievement.getghostblox"
	;
	
	//Spells
	public static final String
	Spell_Fire = "spell.fire",
	Spell_Fira = "spell.fira",
	Spell_Firaga = "spell.firaga",
	
	Spell_Blizzard = "spell.blizzard",
	Spell_Blizzara = "spell.blizzara",
	Spell_Blizzaga = "spell.blizzaga",
	
	Spell_Thunder = "spell.thunder",
	Spell_Thundara = "spell.thundara",
	Spell_Thundaga = "spell.thundaga",
	
	Spell_Cure = "spell.cure",
	Spell_Cura = "spell.cura",
	Spell_Curaga = "spell.curaga",
	
	Spell_Gravity = "spell.gravity",
	Spell_Gravira = "spell.gravira",
	Spell_Graviga = "spell.graviga",
	
	Spell_Aero = "spell.aero",
	Spell_Aerora = "spell.aerora",
	Spell_Aeroga = "spell.aeroga",
	
	Spell_Stop = "spell.stop",
	Spell_Stopra = "spell.stopra",
	Spell_Stopga = "spell.stopga"
	;
	
	//Forms
	public static final String
	Form_Valor = "form.valor",
	Form_Wisdom = "form.wisdom",
	Form_Limit = "form.limit",
	Form_Master = "form.master",
	Form_Final = "form.final",
	Form_Anti = "form.anti"
	;
	
	// Gui
	public static final String
	// Command Menu
	Gui_CommandMenu = "gui.commandmenu",
	Gui_CommandMenu_Command = Gui_CommandMenu + ".command",
	Gui_CommandMenu_Attack = Gui_CommandMenu + ".attack",
	Gui_CommandMenu_Magic = Gui_CommandMenu + ".magic",
	Gui_CommandMenu_Items = Gui_CommandMenu + ".items",
	Gui_CommandMenu_Drive = Gui_CommandMenu + ".drive",
	Gui_CommandMenu_Drive_Revert = Gui_CommandMenu_Drive + ".revert",
	Gui_CommandMenu_Magic_Title = Gui_CommandMenu_Magic + ".title",

	Gui_CommandMenu_Drive_Title = Gui_CommandMenu_Drive + ".title",

	// Menu
	Gui_Menu = "gui.menu", 
	Gui_Menu_Main = Gui_Menu + ".main",
	Gui_Menu_Main_Title = Gui_Menu_Main + ".title",
	Gui_Menu_Main_Button = Gui_Menu_Main + ".button",
	Gui_Menu_Main_Button_Items = Gui_Menu_Main_Button + ".items",
	Gui_Menu_Main_Button_Abilities = Gui_Menu_Main_Button + ".abilities",
	Gui_Menu_Main_Button_Customize = Gui_Menu_Main_Button + ".customize",
	Gui_Menu_Main_Button_Party = Gui_Menu_Main_Button + ".party",
	Gui_Menu_Main_Button_Status = Gui_Menu_Main_Button + ".status",
	Gui_Menu_Main_Button_Journal = Gui_Menu_Main_Button + ".journal",
	Gui_Menu_Main_Button_Config = Gui_Menu_Main_Button + ".config",
	Gui_Menu_Main_Time = Gui_Menu_Main + ".time",
	Gui_Menu_Items = Gui_Menu + ".items",
	Gui_Menu_Items_Title = Gui_Menu_Items + ".title",
	Gui_Menu_Items_Button_Keychain = Gui_Menu_Items + ".keychain",
	Gui_Menu_Items_Button_Potions = Gui_Menu_Items + ".potions",
	Gui_Menu_Items_Button_Spells = Gui_Menu_Items + ".spells",
	Gui_Menu_Items_Button_Drive = Gui_Menu_Items + ".drives",
	Gui_Menu_Items_Button = Gui_Menu_Items + ".button",
	Gui_Menu_Items_Button_Stock = Gui_Menu_Items_Button + ".stock",
	Gui_Menu_Items_Button_Back = Gui_Menu_Items_Button + ".back",
	Gui_Menu_Main_Munny = Gui_Menu_Main + ".munny",
	Gui_Menu_Config = Gui_Menu + ".config",
	Gui_Menu_Config_Title = Gui_Menu_Config + ".title",
	Gui_Menu_Config_Colour = Gui_Menu_Config + ".colour",
	Gui_Menu_Config_Colour_Desc = Gui_Menu_Config_Colour + ".desc",
	Gui_Menu_Config_Hearts = Gui_Menu_Config + ".hearts",
	Gui_Menu_Config_Music = Gui_Menu_Config + ".music",
	Gui_Menu_Config_Fire = Gui_Menu_Config + ".fire",

	// Shop
	Gui_Shop = "gui.shop",
	Gui_Shop_Main = Gui_Shop + ".main",
	Gui_Shop_Main_Title = Gui_Shop_Main + ".title",
	Gui_Shop_Main_Buy = Gui_Shop_Main + ".buy",
	Gui_Shop_Main_Sell = Gui_Shop_Main + ".sell",
	Gui_Shop_Buy = Gui_Shop + ".buy",
	Gui_Shop_Buy_Cost = Gui_Shop_Buy + ".cost",
	Gui_Shop_Buy_Quantity = Gui_Shop_Buy + ".quantity",
	Gui_Shop_Sell = Gui_Shop + ".sell",
	Gui_Shop_Sell_Price = Gui_Shop_Sell + ".price",

	// Synthesis
	Gui_Synthesis = "gui.synthesis",
	Gui_Synthesis_Main = Gui_Synthesis + ".main",
	Gui_Synthesis_Main_Title = Gui_Synthesis_Main + ".title",
	Gui_Synthesis_Main_Recipes = Gui_Synthesis_Main + ".recipes",
	Gui_Synthesis_Main_FreeDev = Gui_Synthesis_Main + ".freedevelopment",
	Gui_Synthesis_Main_Materials = Gui_Synthesis_Main + ".materials",
	Gui_Synthesis_Main_Materials_Deposit = Gui_Synthesis_Main_Materials + ".deposit",
	Gui_Synthesis_Main_Materials_Deposit_Inv = Gui_Synthesis_Main_Materials_Deposit + ".inventory",
	Gui_Synthesis_Main_Materials_Deposit_Bag = Gui_Synthesis_Main_Materials_Deposit + ".bag",
	Gui_Synthesis_Main_Materials_TakeOne = Gui_Synthesis_Main_Materials + ".takeone",
	Gui_Synthesis_Main_Materials_TakeHalfStack = Gui_Synthesis_Main_Materials + ".takehalfstack",
	Gui_Synthesis_Main_Materials_TakeStack = Gui_Synthesis_Main_Materials + ".takestack",
	Gui_Synthesis_Main_Materials_TakeAll = Gui_Synthesis_Main_Materials + ".takeall",
	Gui_Synthesis_Main_Recipes_ReqMaterials = Gui_Synthesis_Main_Recipes + ".requiredmaterials",
	Gui_Synthesis_Main_Recipes_Create = Gui_Synthesis_Main_Recipes + ".create";

	//Chat Messages
	public static final String
	Chat_Recipe_Learn = "chat.recipeLearn",
	Chat_Recipe_Repeat = "chat.recipeRepeat",
	SavePointSave = "chat.savePointSave",
	ChestLockSuccess = "chat.chestLockSuccess",
	ChestLocked = "chat.chestLocked",
	Chat_Magic_Learn = "chat.magic.learn",
	Chat_Magic_Error = "chat.magic.error",
	Chat_Magic_Levelup = "chat.magic.levelup",
	Chat_Drive_Learn = "chat.drive.learn",
	Chat_Drive_Error = "chat.drive.error",
	Chat_Manifest = "chat.manifest.learn",
	Chat_PowerBoost = "chat.powerboost",
	Chat_DefenseBoost = "chat.defenseboost",
	Chat_MagicBoost = "chat.magicboost"
	;
	
	//Stats
	public static final String
	Stats_LevelUp_Str = "stats.levelUpStr",
	Stats_LevelUp_Def = "stats.levelUpDef",
	Stats_LevelUp_Magic = "stats.levelUpMag",
	Stats_LevelUp_HP = "stats.levelUpHP"
	;
	
	// Blocks
	public static final String
	// Blox
	NormalBlox = "normalblox", 
	HardBlox = "hardblox", 
	MetalBlox = "metalblox",
	DangerBlox = "dangerblox", 
	BounceBlox = "bounceblox",
	BlastBlox = "blastblox", 
	PrizeBlox = "prizeblox",
	RarePrizeBlox = "rareprizeblox", 
	GhostBlox = "ghostblox",
	MagnetBlox = "magnetblox",
	Shop = "shop",

	KKChest = "kkchest",
	Pedestal = "pedestal",

	// Ores
	BlazingOre = "blazingore", 
	BrightOre = "brightore", 
	DarkOre = "darkore",
	DarkOreE = "darkoree", 
	DenseOre = "denseore", 
	EnergyOre = "energyore",
	FrostOre = "frostore", 
	LucidOre = "lucidore", 
	LightningOre = "lightningore",
	PowerOre = "powerore", 
	PowerOreE = "poweroree",
	RemembranceOre = "remembranceore", 
	SerenityOre = "serenityore",
	StormyOre = "stormyore", 
	TranquilOre = "tranquilore",
	TwilightOre = "twilightore",

	// Others
	SynthesisTable = "synthesistable", 
	SavePoint = "savepoint",
	StationOfAwakening = "stationofawakening",
	StationOfAwakeningDoor = "stationofawakeningdoor"
	;

	// Tooltips
	public static final String 
	HoldForInfo = "holdforinfo.desc",
	GhostBloxDesc = "tile.ghostblox.desc",
	DangerBloxDesc = "tile.dangerblox.desc",
	BounceBloxDesc = "tile.bounceblox.desc",
	KKChestDesc_1 = "tile.kkchest.desc1", 
	KKChestDesc_2 = "tile.kkchest.desc2",
	SavePointDesc = "tile.savepoint.desc", 
	SynthesisBagDesc = "synthesisbag.desc"
	;

	// Items
	public static final String 
	Munny = "munny", 
	EmptyBottle = "emptybottle",
	Potion = "potion",
	HiPotion = "hipotion",
	MegaPotion = "megapotion",
	Ether = "ether",
	MegaEther = "megaether",
	Elixir = "elixir",
	Megalixir = "megalixir",
	DriveRecovery = "driverecovery",
	HighDriveRecovery = "highdriverecovery",
	DefenseBoost = "defenseboost",
	MagicBoost = "magicboost",
	PowerBoost = "powerboost",
	Panacea = "panacea",
	HpOrb = "hporb",
	DriveOrb = "driveorb", 
	MagicOrb = "magicorb", 
	Heart = "heart",
	DarkHeart = "darkheart", 
	PureHeart = "pureheart",
	KingdomHearts = "kingdomhearts", 
	DarkLeather = "darkleather",
	SynthesisMaterial = "synthesismaterial", 
	Recipe = "recipe",
	LunaticDesc = "item.lunatic.desc", 
	IceCream = "icecream",
	WinnerStick = "winnerstick", 
	LevelUpMagicFire = "levelupmagicfire",
	LevelUpMagicBlizzard = "levelupmagicblizzard",
	LevelUpMagicThunder = "levelupmagicthunder",
	LevelUpMagicCure = "levelupmagiccure",
	LevelUpMagicAero = "levelupmagicaero",
	LevelUpMagicStop = "levelupmagicstop", 
	LevelUpValor = "levelupdrivevalor",
	LevelUpWisdom = "levelupdrivewisdom", 
	LevelUpLimit = "levelupdrivelimit",
	LevelUpMaster = "levelupdrivemaster", 
	LevelUpFinal = "levelupdrivefinal",
	SynthesisBagS = "synthesisbags", 
	SynthesisBagM = "synthesisbagm",
	SynthesisBagL = "synthesisbagl"
	;

	public static final String 
	BlazingInfusedCoal = "blazinginfusedcoal",
	FrostInfusedSnowBall = "frostinfusedsnowball",
	StormyInfusedIron = "stormyinfusediron",
	MythrilInfusedDiamond = "mythrilinfuseddiamond",
	LightningInfusedGold = "lightninginfusedgold",
	BrightInfusedGlowStone = "brightinfusedglowstone",
	DarkInfusedIron = "darkinfusediron";

	// Armour
	public static final String 
	OrganizationRobe_Helmet = "organizationrobe_helmet",
	OrganizationRobe_Chestplate = "organizationrobe_chestplate",
	OrganizationRobe_Leggings = "organizationrobe_leggings",
	OrganizationRobe_Boots = "organizationrobe_boots",

	Terra_Helmet = "terra_helmet", 
	Terra_Chestplate = "terra_chestplate",
	Terra_Leggings = "terra_leggings", 
	Terra_Boots = "terra_boots",

	Aqua_Helmet = "aqua_helmet", 
	Aqua_Chestplate = "aqua_chestplate",
	Aqua_Leggings = "aqua_leggings", 
	Aqua_Boots = "aqua_boots",

	Ventus_Helmet = "ventus_helmet", 
	Ventus_Chestplate = "ventus_chestplate",
	Ventus_Leggings = "ventus_leggings", 
	Ventus_Boots = "ventus_boots",

	Eraqus_Helmet = "eraqus_helmet", 
	Eraqus_Chestplate = "eraqus_chestplate",
	Eraqus_Leggings = "eraqus_leggings", 
	Eraqus_Boots = "eraqus_boots";

	// Synthesis Materials
	public static final String 
	SM_Rank = "sm.rank",
	SM_Rank_C = SM_Rank + ".c",
	SM_Rank_B = SM_Rank + ".b",
	SM_Rank_A = SM_Rank + ".a",
	SM_Rank_S = SM_Rank + ".s",
	SM_BlazingShard = "sm.blazingshard", 
	SM_BlazingStone = "sm.blazingstone",
	SM_BlazingGem = "sm.blazinggem", 
	SM_BlazingCrystal = "sm.blazingcrystal",

	SM_BrightShard = "sm.brightshard", 
	SM_BrightStone = "sm.brightstone",
	SM_BrightGem = "sm.brightgem", 
	SM_BrightCrystal = "sm.brightcrystal",

	SM_DarkShard = "sm.darkshard", 
	SM_DarkStone = "sm.darkstone",
	SM_DarkGem = "sm.darkgem", 
	SM_DarkCrystal = "sm.darkcrystal",

	SM_DenseShard = "sm.denseshard", 
	SM_DenseStone = "sm.densestone",
	SM_DenseGem = "sm.densegem", 
	SM_DenseCrystal = "sm.densecrystal",

	SM_EnergyShard = "sm.energyshard", 
	SM_EnergyStone = "sm.energystone",
	SM_EnergyGem = "sm.energygem", 
	SM_EnergyCrystal = "sm.energycrystal",

	SM_FrostShard = "sm.frostshard", 
	SM_FrostStone = "sm.froststone",
	SM_FrostGem = "sm.frostgem", 
	SM_FrostCrystal = "sm.frostcrystal",

	SM_LightningShard = "sm.lightningshard",
	SM_LightningStone = "sm.lightningstone",
	SM_LightningGem = "sm.lightninggem",
	SM_LightningCrystal = "sm.lightningcrystal",

	SM_LucidShard = "sm.lucidshard", 
	SM_LucidStone = "sm.lucidstone",
	SM_LucidGem = "sm.lucidgem", 
	SM_LucidCrystal = "sm.lucidcrystal",

	SM_PowerShard = "sm.powershard", 
	SM_PowerStone = "sm.powerstone",
	SM_PowerGem = "sm.powergem", 
	SM_PowerCrystal = "sm.powercrystal",

	SM_MythrilShard = "sm.mythrilshard", 
	SM_MythrilStone = "sm.mythrilstone",
	SM_MythrilGem = "sm.mythrilgem", 
	SM_MythrilCrystal = "sm.mythrilcrystal",

	SM_RemembranceShard = "sm.remembranceshard",
	SM_RemembranceStone = "sm.remembrancestone",
	SM_RemembranceGem = "sm.remembrancegem",
	SM_RemembranceCrystal = "sm.remembrancecrystal",

	SM_SerenityShard = "sm.serenityshard",
	SM_SerenityStone = "sm.serenitystone", 
	SM_SerenityGem = "sm.serenitygem",
	SM_SerenityCrystal = "sm.serenitycrystal",

	SM_TranquilShard = "sm.tranquilshard",
	SM_TranquilStone = "sm.tranquilstone", 
	SM_TranquilGem = "sm.tranquilgem",
	SM_TranquilCrystal = "sm.tranquilcrystal",

	SM_TwilightShard = "sm.twilightshard",
	SM_TwilightStone = "sm.twilightstone", 
	SM_TwilightGem = "sm.twilightgem",
	SM_TwilightCrystal = "sm.twilightcrystal",

	SM_Orichalcum = "sm.orichalcum", 
	SM_OrichalcumPlus = "sm.orichalcum+",
	SM_ManifestIllusion = "sm.manifestillusion",
	SM_LostIllusion = "sm.lostillusion",

	SM_StormyShard = "sm.stormyshard", 
	SM_StormyStone = "sm.stormystone",
	SM_StormyGem = "sm.stormygem", 
	SM_StormyCrystal = "sm.stormycrystal"
	;

	// Music Discs
	public static final String 
	Disc_Birth_by_Sleep_A_Link_to_the_Future = "birthbysleep-alinktothefuture-",
	Disc_Darkness_of_the_Unknown = "darknessoftheunknown",
	Disc_Dearly_Beloved_Symphony_Version = "dearlybeloved-symphonyversion-",
	Disc_Dream_Drop_Distance_The_Next_Awakening = "dreamdropdistance-thenextawakening-",
	Disc_Hikari_KINGDOM_Instrumental_Version = "hikari-kingdominstrumentalversion-",
	Disc_L_Oscurita_Dell_Ignoto = "l'oscuritadell'ignoto",
	Disc_Musique_pour_la_tristesse_de_Xion = "musiquepourlatristessedexion",
	Disc_No_More_Bugs_Bug_Version = "nomorebugs-bugversion-",
	Disc_Organization_XIII = "organizationxiii", Disc_Sanctuary = "sanctuary",
	Disc_Simple_And_Clean_PLANITb_Remix = "simpleandcleanplanitbremix",
	Disc_Sinister_Sundown = "sinistersundown",
	Disc_The_13th_Anthology = "the13thanthology"
	;

	// Organization
	public static final String 
	Interdiction = "interdiction",
	Sharpshooter = "sharpshooter", 
	Lindworm = "lindworm",
	FrozenPride = "frozenpride", 
	Skysplitter = "skysplitter",
	BookofRetribution = "bookofretribution", 
	Lunatic = "lunatic",
	EternalFlames = "eternalflames", 
	Arpeggio = "arpeggio",
	FairGame = "fairgame", 
	GracefulDahlia = "gracefuldahlia", 
	Foudre = "foudre",
	BlazeofGlory = "blazeofglory", 
	Prometheus = "prometheus", 
	Ifrit = "ifrit",
	Prominence = "prominence",
	FickleErica = "fickleerica",
	PoorMelissa = "poormelissa",
	JiltedAnemone = "jiltedanemone",
	Standalone = "standalone",
	Zephyr = "zephyr",
	Reticence = "reticence",
	FinalWeapon = "finalweapon",
    Tranchant = "tranchant",
    Malice = "malice",
    Infinity = "infinity",
    TheFool = "thefool",
    TesterZero = "testerzero",
    Calmant = "calmant"
	;

	public static final String 
	AbandonedKnowledge = "abandonedknowledge",
	DarkKnowledge = "darkknowledge", 
	EclipsedKnowledge = "eclipsedknowledge",
	ForgottenKnowledge = "forgottenknowledge",
	IlludedKnowledge = "illudedknowledge", 
	LostKnowledge = "lostknowledge",
	ManifestKnowledge = "manifestknowledge",
	ObscuredKnowledge = "obscuredknowledge",
	UnknownKnowledge = "unknownknowledge", 
	VoidKnowledge = "voidknowledge"
	;

	// Keyblades
	public static final String 
	KingdomKey = "kingdomkey",
	Oathkeeper = "oathkeeper", 
	Oblivion = "oblivion",
	UltimaWeaponKH1 = "ultimaweaponkh1", 
	KingdomKeyD = "kingdomkeyd",
	KeybladeofPeoplesHearts = "keybladeofpeopleshearts", 
	LadyLuck = "ladyluck",
	Olympia = "olympia", 
	JungleKing = "jungleking", 
	ThreeWishes = "threewishes",
	Crabclaw = "crabclaw", 
	FairyHarp = "fairyharp", 
	DivineRose = "divinerose",
	Spellbinder = "spellbinder", 
	MetalChocobo = "metalchocobo",
	Lionheart = "lionheart", 
	DiamondDust = "diamonddust",
	OneWingedAngel = "onewingedangel", 
	SoulEater = "souleater",
	Pumpkinhead = "pumpkinhead", 
	WishingStar = "wishingstar",
	BondofFlame = "bondofflame", 
	FollowtheWind = "followthewind",
	HiddenDragon = "hiddendragon", 
	Monochrome = "monochrome",
	PhotonDebugger = "photondebugger", 
	StarSeeker = "starseeker",
	MaverickFlare = "maverickflare", 
	TotalEclipse = "totaleclipse",
	MidnightRoar = "midnightroar", 
	TwoBecomeOne = "twobecomeone",
	UltimaWeaponKH2 = "ultimaweaponkh2", 
	WaytotheDawn = "waytothedawn",
	DestinysEmbrace = "destinysembrace", 
	Stormfall = "stormfall",
	EndsoftheEarth = "endsoftheearth", 
	RumblingRose = "rumblingrose",
	HerosCrest = "heroscrest", 
	MysteriousAbyss = "mysteriousabyss",
	WishingLamp = "wishinglamp", 
	DecisivePumpkin = "decisivepumpkin",
	CircleofLife = "circleoflife", 
	SweetMemories = "sweetmemories",
	GullWing = "gullwing", 
	GuardianSoul = "guardiansoul",
	SleepingLion = "sleepinglion", 
	Fenrir = "fenrir", 
	FatalCrest = "fatalcrest",
	WinnersProof = "winnersproof", 
	MissingAche = "missingache",
	OminousBlight = "ominousblight", 
	AbaddonPlasma = "abaddonplasma",
	PainofSolitude = "painofsolitude", 
	SignofInnocence = "signofinnocence",
	CrownofGuilt = "crownofguilt", 
	AbyssalTide = "abyssaltide",
	Leviathan = "leviathan", 
	TrueLightsFlight = "truelightsflight",
	RejectionofFate = "rejectionoffate",
	GlimpseofDarkness = "glimpseofdarkness", 
	SilentDirge = "silentdirge",
	LunarEclipse = "lunareclipse", 
	DarkerThanDark = "darkerthandark",
	AstralBlast = "astralblast", 
	TwilightBlaze = "twilightblaze",
	OmegaWeapon = "omegaweapon", 
	Umbrella = "umbrella", 
	Aubade = "aubade",
	WoodenStick = "woodenstick", 
	DreamSword = "dreamsword", 
	ZeroOne = "zeroone",
	Earthshaker = "earthshaker", 
	Darkgnaw = "darkgnaw",
	ChaosRipper = "chaosripper",
	MasterXehanortsKeyblade = "masterxehanortskeyblade",
	TreasureTrove = "treasuretrove", 
	StrokeofMidnight = "strokeofmidnight",
	FairyStars = "fairystars", 
	VictoryLine = "victoryline",
	MarkofaHero = "markofahero", 
	Hyperdrive = "hyperdrive",
	PixiePetal = "pixiepetal", 
	Sweetstack = "sweetstack",
	UltimaWeaponBBS = "ultimaweaponbbs", 
	VoidGear = "voidgear",
	NoName = "noname", 
	RoyalRadiance = "royalradiance", 
	Rainfell = "rainfell",
	Brightcrest = "brightcrest", 
	MastersDefender = "mastersdefender",
	WaywardWind = "waywardwind", 
	FrolicFlame = "frolicflame",
	LostMemory = "lostmemory", 
	Kiblade = "kiblade",
	IncompleteKiblade = "incompletekiblade", 
	WoodenKeyblade = "woodenkeyblade",
	SkullNoise = "skullnoise", 
	GuardianBell = "guardianbell",
	DualDisc = "dualdisc", 
	FerrisGear = "ferrisgear",
	KnockoutPunch = "knockoutpunch", 
	AllforOne = "allforone",
	Counterpoint = "counterpoint", 
	Divewing = "divewing",
	SweetDreams = "sweetdreams", 
	UltimaWeaponDDD = "ultimaweaponddd",
	Unbound = "unbound", 
	EndofPain = "endofpain", 
	OceansRage = "oceansrage",
	LeasKeyblade = "leaskeyblade",
	YoungXehanortsKeyblade = "youngxehanortskeyblade",
	MirageSplit = "miragesplit", 
	NightmaresEnd = "nightmaresend",
	NightmaresEndandMirageSplit = "nightmaresendandmiragesplit",
	Starlight = "starlight",
	AnguisForetellersKeyblade = "anguisforetellerskeyblade",
	LeopardosForetellersKeyblade = "leopardosforetellerskeyblade",
	UnicornisForetellersKeyblade = "unicornisforetellerskeyblade",
	UrsusForetellersKeyblade = "ursusforetellerskeyblade",
	VulpeusForetellersKeyblade = "vulpeusforetellerskeyblade"
	;

	// CHAINS
	public static final String 
	Chain_AbaddonPlasma = "abaddonplasmachain",
	Chain_AbyssalTide = "abyssaltidechain", 
	Chain_AllforOne = "allforonechain",
	Chain_AnguisForetellersKeyblade = "anguisforetellerskeybladechain",
	Chain_AstralBlast = "astralblastchain", 
	Chain_Aubade = "aubadechain",
	Chain_BondofFlame = "bondofflamechain",
	Chain_Brightcrest = "brightcrestchain",
	Chain_ChaosRipper = "chaosripperchain",
	Chain_CircleofLife = "circleoflifechain",
	Chain_Counterpoint = "counterpointchain", 
	Chain_Crabclaw = "crabclawchain",
	Chain_CrownofGuilt = "crownofguiltchain",
	Chain_DarkerThanDark = "darkerthandarkchain",
	Chain_Darkgnaw = "darkgnawchain",
	Chain_DecisivePumpkin = "decisivepumpkinchain",
	Chain_DestinysEmbrace = "destinysembracechain",
	Chain_DiamondDust = "diamonddustchain", 
	Chain_Divewing = "divewingchain",
	Chain_DivineRose = "divinerosechain", 
	Chain_DreamSword = "dreamswordchain",
	Chain_DualDisc = "dualdiscchain", 
	Chain_Earthshaker = "earthshakerchain",
	Chain_EndofPain = "endofpainchain",
	Chain_EndsoftheEarth = "endsoftheearthchain",
	Chain_FairyHarp = "fairyharpchain", 
	Chain_FairyStars = "fairystarschain",
	Chain_FatalCrest = "fatalcrestchain", 
	Chain_Fenrir = "fenrirchain",
	Chain_FerrisGear = "ferrisgearchain",
	Chain_FollowtheWind = "followthewindchain",
	Chain_FrolicFlame = "frolicflamechain",
	Chain_GlimpseofDarkness = "glimpseofdarknesschain",
	Chain_GuardianBell = "guardianbellchain",
	Chain_GuardianSoul = "guardiansoulchain", 
	Chain_GullWing = "gullwingchain",
	Chain_HerosCrest = "heroscrestchain",
	Chain_HiddenDragon = "hiddendragonchain",
	Chain_Hyperdrive = "hyperdrivechain",
	Chain_IncompleteKiblade = "incompletekibladechain",
	Chain_JungleKing = "junglekingchain",
	Chain_KeybladeofPeoplesHearts = "keybladeofpeoplesheartschain",
	Chain_Kiblade = "kibladechain", 
	Chain_KingdomKey = "kingdomkeychain",
	Chain_KingdomKeyD = "kingdomkeydchain",
	Chain_KnockoutPunch = "knockoutpunchchain",
	Chain_LadyLuck = "ladyluckchain", 
	Chain_LeasKeyblade = "leaskeybladechain",
	Chain_LeopardosForetellersKeyblade = "leopardosforetellerskeybladechain",
	Chain_Leviathan = "leviathanchain", 
	Chain_Lionheart = "lionheartchain",
	Chain_LostMemory = "lostmemorychain",
	Chain_LunarEclipse = "lunareclipsechain",
	Chain_MarkofaHero = "markofaherochain",
	Chain_MasterXehanortsKeyblade = "masterxehanortskeybladechain",
	Chain_MastersDefender = "mastersdefenderchain",
	Chain_MaverickFlare = "maverickflarechain",
	Chain_MetalChocobo = "metalchocobochain",
	Chain_MidnightRoar = "midnightroarchain",
	Chain_MirageSplit = "miragesplitchain",
	Chain_MissingAche = "missingachechain",
	Chain_Monochrome = "monochromechain",
	Chain_MysteriousAbyss = "mysteriousabysschain",
	Chain_NightmaresEnd = "nightmaresendchain",
	Chain_NightmaresEndandMirageSplit = "nightmaresendandmiragesplitchain",
	Chain_NoName = "nonamechain", 
	Chain_Oathkeeper = "oathkeeperchain",
	Chain_Oblivion = "oblivionchain", 
	Chain_OceansRage = "oceansragechain",
	Chain_Olympia = "olympiachain", 
	Chain_OmegaWeapon = "omegaweaponchain",
	Chain_OminousBlight = "ominousblightchain",
	Chain_OneWingedAngel = "onewingedangelchain",
	Chain_PainofSolitude = "painofsolitudechain",
	Chain_PhotonDebugger = "photondebuggerchain",
	Chain_PixiePetal = "pixiepetalchain",
	Chain_Pumpkinhead = "pumpkinheadchain", 
	Chain_Rainfell = "rainfellchain",
	Chain_RejectionofFate = "rejectionoffatechain",
	Chain_RoyalRadiance = "royalradiancechain",
	Chain_RumblingRose = "rumblingrosechain",
	Chain_SignofInnocence = "signofinnocencechain",
	Chain_SilentDirge = "silentdirgechain",
	Chain_SkullNoise = "skullnoisechain",
	Chain_SleepingLion = "sleepinglionchain",
	Chain_SoulEater = "souleaterchain", 
	Chain_Spellbinder = "spellbinderchain",
	Chain_StarSeeker = "starseekerchain", 
	Chain_Starlight = "starlightchain",
	Chain_Stormfall = "stormfallchain",
	Chain_StrokeofMidnight = "strokeofmidnightchain",
	Chain_SweetDreams = "sweetdreamschain",
	Chain_SweetMemories = "sweetmemorieschain",
	Chain_Sweetstack = "sweetstackchain",
	Chain_ThreeWishes = "threewisheschain",
	Chain_TotalEclipse = "totaleclipsechain",
	Chain_TreasureTrove = "treasuretrovechain",
	Chain_TrueLightsFlight = "truelightsflightchain",
	Chain_TwilightBlaze = "twilightblazechain",
	Chain_TwoBecomeOne = "twobecomeonechain",
	Chain_UltimaWeaponKH1 = "ultimaweaponkh1chain",
	Chain_UltimaWeaponKH2 = "ultimaweaponkh2chain",
	Chain_UltimaWeaponBBS = "ultimaweaponbbschain",
	Chain_UltimaWeaponDDD = "ultimaweapondddchain",
	Chain_Umbrella = "umbrellachain", 
	Chain_Unbound = "unboundchain",
	Chain_UnicornisForetellersKeyblade = "unicornisforetellerskeybladechain",
	Chain_UrsusForetellersKeyblade = "ursusforetellerskeybladechain",
	Chain_VictoryLine = "victorylinechain", 
	Chain_VoidGear = "voidgearchain",
	Chain_VulpeusForetellersKeyblade = "vulpeusforetellerskeybladechain",
	Chain_WaytotheDawn = "waytothedawnchain",
	Chain_WaywardWind = "waywardwindchain",
	Chain_WinnersProof = "winnersproofchain",
	Chain_WishingLamp = "wishinglampchain",
	Chain_WishingStar = "wishingstarchain",
	Chain_YoungXehanortsKeyblade = "youngxehanortskeybladechain",
	Chain_ZeroOne = "zeroonechain"
	;

	public static final String 
	KKChestInventory = "container.kkchest",
	KeychainInventory = "container.keychain",
	SynthesisBagSInventory = "container.synthesisbagsinventory",
	SynthesisBagMInventory = "container.synthesisbagminventory",
	SynthesisBagLInventory = "container.synthesisbaglinventory",
	SpellsInventory = "container.spellsinventory",
	DriveInventory = "container.driveinventory",
	PotionsInventory = "container.potionsinventory"
	;
}
